interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
    "**/backup_before_rename",  # Add this line
    "backup_before_rename/**",   # And this for good measure
]
source_roots = [
    ".", "src",
]

[[modules ]]
path = "src.decompile"
depends_on = ["src.model", "src.generate", "src.extract"]

[[modules ]]
path = "src.base"
depends_on = []
utility = true

[[modules ]]
path = "src.types"
depends_on = []
utility = true

[[modules ]]
path = "src.contracts"
depends_on = []
utility = true

[[modules ]]
path = "src.pipeline"
depends_on = []
utility = true

[[modules ]]
path = "src.model"
depends_on = []

[[modules ]]
path = "src.parse"
depends_on = ["src.extract", "src.model"]

[[modules ]]
path = "src.extract"
depends_on = ["src.decompile"]

[[modules ]]
path = "src.common"
depends_on = ["src.generate", "src.parse", "src.decompile", "src.extract", "src.model"]
utility = true

[[modules ]]
path = "src.generate"
depends_on = ["src.model", "src.parse"]
