// Unified PowerBuilder P-code opcode definitions
// Generated from multiple reference implementations

using System;
using System.Collections.Generic;

namespace SimeFinch.Decompiler
{
    public enum Opcode : ushort
    {
        RETURN = 0x00,
        STORE_RETURN_VAL = 0x01,
        JUMPTRUE = 0x02,
        JUMPFALSE = 0x03,
        JUMP = 0x04,
        DBSTART = 0x05,
        DBCOMMIT = 0x06,
        DBROLLBACK = 0x07,
        DBSTOP = 0x08,
        DBCLOSE = 0x09,
        DBOPEN = 0x0A,
        DBDELETE = 0x0B,
        DBUPDATE = 0x0C,
        DBEXECUTE = 0x0D,
        DBFETCH = 0x0E,
        DBINSERT = 0x0F,
        DBSELECT = 0x10,
        DESTROY = 0x11,
        HALT = 0x12,
        EVENTCALL = 0x13,
        LVALUE_EXPR = 0x14,
        DBEXECUTEDYN = 0x15,
        DBPREPARE = 0x16,
        DBOPENDYN = 0x17,
        DBEXECDYNPROC = 0x18,
        DBDESCRIBE = 0x19,
        DBSELECTBLOB = 0x1A,
        DBUPDATEBLOB = 0x1B,
        DBSELECTCLOB = 0x1C,
        DBUPDATECLOB = 0x1D,
        PUSH_LOCAL_VAR = 0x1E,
        PUSH_SHARED_VAR = 0x1F,
        PUSH_CONST_REF = 0x20,
        PUSH_THIS = 0x21,
        PUSH_PARENT = 0x22,
        PUSH_PRIMARY = 0x23,
        AND = 0x24,
        OR = 0x25,
        NOT = 0x26,
        DOT = 0x27,
        INDEX = 0x28,
        GLOBFUNCCALL = 0x29,
        CALL_FUNCTION = 0x2A,
        DLLFUNCCALL = 0x2B,
        DOTFUNCCALL = 0x2C,
        PUSH_GLOBAL_VAR = 0x2D,
        ARRAYLIST = 0x2E,
        PUSH_SHARED_VAR = 0x2F,
        PUSH_LOCAL_ARGREF = 0x30,
        PUSH_SHARED_GLOBREF = 0x31,
        PUSH_CONST_INT = 0x32,
        PUSH_CONST_UINT = 0x33,
        PUSH_CONST_LONG = 0x34,
        PUSH_CONST_ULONG = 0x35,
        PUSH_CONST_DEC = 0x36,
        PUSH_CONST_FLOAT = 0x37,
        PUSH_CONST_DOUBLE = 0x38,
        PUSH_CONST_TIME = 0x39,
        PUSH_CONST_DATE = 0x3A,
        PUSH_CONST_STRING = 0x3B,
        PUSH_CONST_BOOL = 0x3C,
        PUSH_CONST_ENUM = 0x3D,
        CNV_INT_TO_UINT = 0x3E,
        CNV_INT_TO_LONG = 0x3F,
        CNV_INT_TO_ULONG = 0x40,
        CNV_INT_TO_DEC = 0x41,
        CNV_INT_TO_FLOAT = 0x42,
        CNV_INT_TO_DOUBLE = 0x43,
        CNV_UINT_TO_LONG = 0x44,
        CNV_UINT_TO_ULONG = 0x45,
        CNV_UINT_TO_DEC = 0x46,
        CNV_UINT_TO_FLOAT = 0x47,
        CNV_UINT_TO_DOUBLE = 0x48,
        CNV_LONG_TO_ULONG = 0x49,
        CNV_LONG_TO_DEC = 0x4A,
        CNV_LONG_TO_FLOAT = 0x4B,
        CNV_LONG_TO_DOUBLE = 0x4C,
        CNV_ULONG_TO_DEC = 0x4D,
        CNV_ULONG_TO_FLOAT = 0x4E,
        CNV_ULONG_TO_DOUBLE = 0x4F,
        CNV_DEC_TO_FLOAT = 0x50,
        CNV_DEC_TO_DOUBLE = 0x51,
        CNV_FLOAT_TO_DOUBLE = 0x52,
        ADD_INT = 0x53,
        ADD_UINT = 0x54,
        ADD_LONG = 0x55,
        ADD_ULONG = 0x56,
        ADD_DEC = 0x57,
        ADD_FLOAT = 0x58,
        ADD_DOUBLE = 0x59,
        SUB_INT = 0x5A,
        SUB_UINT = 0x5B,
        SUB_LONG = 0x5C,
        SUB_ULONG = 0x5D,
        SUB = 0x5E,
        SUB_FLOAT = 0x5F,
        SUB_DOUBLE = 0x60,
        MULT_INT = 0x61,
        MULT_UINT = 0x62,
        MULT_LONG = 0x63,
        MULT_ULONG = 0x64,
        MULT_DEC = 0x65,
        MULT_FLOAT = 0x66,
        MULT_DOUBLE = 0x67,
        DIV_INT = 0x68,
        DIV_UINT = 0x69,
        DIV_LONG = 0x6A,
        DIV_ULONG = 0x6B,
        DIV = 0x6C,
        DIV_FLOAT = 0x6D,
        DIV_DOUBLE = 0x6E,
        POWER_INT = 0x6F,
        POWER_UINT = 0x70,
        POWER_LONG = 0x71,
        POWER_ULONG = 0x72,
        POWER_DEC = 0x73,
        POWER_FLOAT = 0x74,
        POWER_DOUBLE = 0x75,
        NEGATE_INT = 0x76,
        NEGATE_UINT = 0x77,
        NEGATE_LONG = 0x78,
        NEGATE_ULONG = 0x79,
        NEGATE_DEC = 0x7A,
        NEGATE_FLOAT = 0x7B,
        ADD = 0x7C,
        CAT_STRING = 0x7D,
        CAT_BINARY = 0x7E,
        ASSIGN_ARRAY = 0x7F,
        ASSIGN_INT = 0x80,
        ASSIGN_UINT = 0x81,
        ASSIGN_LONG = 0x82,
        ASSIGN_ULONG = 0x83,
        ASSIGN_DEC = 0x84,
        ASSIGN_FLOAT = 0x85,
        ASSIGN_DOUBLE = 0x86,
        ASSIGN_BLOB = 0x87,
        ASSIGN_STRING = 0x88,
        ASSIGN_TIME = 0x89,
        ASSIGN_OBINST = 0x8A,
        ASSIGN_ANCESTOR = 0x8B,
        ASSIGN_ENUM = 0x8C,
        CNV_UINT_TO_INT = 0x8D,
        CNV_LONG_TO_INT = 0x8E,
        CNV_ULONG_TO_INT = 0x8F,
        CNV_DEC_TO_INT = 0x90,
        CNV_FLOAT_TO_INT = 0x91,
        CNV_DOUBLE_TO_INT = 0x92,
        CNV_LONG_TO_UINT = 0x93,
        CNV_ULONG_TO_UINT = 0x94,
        CNV_DEC_TO_UINT = 0x95,
        CNV_FLOAT_TO_UINT = 0x96,
        CNV_DOUBLE_TO_UINT = 0x97,
        CNV_ULONG_TO_LONG = 0x98,
        CNV_DEC_TO_LONG = 0x99,
        CNV_FLOAT_TO_LONG = 0x9A,
        CNV_DOUBLE_TO_LONG = 0x9B,
        CNV_DEC_TO_ULONG = 0x9C,
        CNV_FLOAT_TO_ULONG = 0x9D,
        CNV_DOUBLE_TO_ULONG = 0x9E,
        CNV_FLOAT_TO_DEC = 0x9F,
        CNV_DOUBLE_TO_DEC = 0xA0,
        CNV_DOUBLE_TO_FLOAT = 0xA1,
        CNV_STRING_TO_CHAR = 0xA2,
        CNV_CHAR_TO_STRING = 0xA3,
        CNV_STRING_TO_CHARARRAY = 0xA4,
        CNV_CHARARRAY_TO_STRING = 0xA5,
        EQ_INT = 0xA6,
        EQ_UINT = 0xA7,
        EQ_LONG = 0xA8,
        EQ_ULONG = 0xA9,
        EQ_DEC = 0xAA,
        EQ_FLOAT = 0xAB,
        EQ_DOUBLE = 0xAC,
        EQ_STRING = 0xAD,
        EQ_BOOL = 0xAE,
        EQ_BINARY = 0xAF,
        EQ_TIME = 0xB0,
        EQ_DATE = 0xB1,
        EQ_DATETIME = 0xB2,
        EQ_CHAR = 0xB3,
        EQ_OBINST = 0xB4,
        EQ_ENUM = 0xB5,
        NE_INT = 0xB6,
        NE_UINT = 0xB7,
        NE_LONG = 0xB8,
        NE_ULONG = 0xB9,
        NE_DEC = 0xBA,
        NE_FLOAT = 0xBB,
        NE_DOUBLE = 0xBC,
        NE_STRING = 0xBD,
        NE_BOOL = 0xBE,
        NE_BINARY = 0xBF,
        NE_TIME = 0xC0,
        NE_DATE = 0xC1,
        NE_DATETIME = 0xC2,
        NE_CHAR = 0xC3,
        NE_OBINST = 0xC4,
        NE_ENUM = 0xC5,
        GT_INT = 0xC6,
        GT_UINT = 0xC7,
        GT_LONG = 0xC8,
        GT_ULONG = 0xC9,
        GT_DEC = 0xCA,
        GT_FLOAT = 0xCB,
        GT_DOUBLE = 0xCC,
        GT_STRING = 0xCD,
        GT_TIME = 0xCE,
        GT = 0xCF,
        GT_DATETIME = 0xD0,
        GT_CHAR = 0xD1,
        LT_INT = 0xD2,
        LT_UINT = 0xD3,
        LT_LONG = 0xD4,
        LT_ULONG = 0xD5,
        LT_DEC = 0xD6,
        LT_FLOAT = 0xD7,
        LT_DOUBLE = 0xD8,
        LT_STRING = 0xD9,
        LT_TIME = 0xDA,
        LT_DATE = 0xDB,
        LT_DATETIME = 0xDC,
        LT_CHAR = 0xDD,
        GE_INT = 0xDE,
        GE_UINT = 0xDF,
        GE_LONG = 0xE0,
        GE_ULONG = 0xE1,
        GE_DEC = 0xE2,
        GE_FLOAT = 0xE3,
        GE_DOUBLE = 0xE4,
        GE_STRING = 0xE5,
        GE_TIME = 0xE6,
        GE = 0xE7,
        GE_DATETIME = 0xE8,
        GE_CHAR = 0xE9,
        LE_INT = 0xEA,
        LE_UINT = 0xEB,
        LE_LONG = 0xEC,
        LE_ULONG = 0xED,
        LE_DEC = 0xEE,
        LE_FLOAT = 0xEF,
        LE_DOUBLE = 0xF0,
        LE_STRING = 0xF1,
        LE_TIME = 0xF2,
        LE = 0xF3,
        LE_DATETIME = 0xF4,
        LE_CHAR = 0xF5,
        INCR_INT = 0xF6,
        INCR_UINT = 0xF7,
        INCR_LONG = 0xF8,
        INCR_ULONG = 0xF9,
        INCR_DEC = 0xFA,
        INCR_FLOAT = 0xFB,
        INCR_DOUBLE = 0xFC,
        DECR_INT = 0xFD,
        DECR_UINT = 0xFE,
        DECR_LONG = 0xFF,
        DECR_ULONG = 0x100,
        DECR_DEC = 0x101,
        DECR_FLOAT = 0x102,
        DECR_DOUBLE = 0x103,
        ADDASSIGN_INT = 0x104,
        ADDASSIGN_UINT = 0x105,
        ADDASSIGN_LONG = 0x106,
        ADDASSIGN_ULONG = 0x107,
        ADDASSIGN_DEC = 0x108,
        ADDASSIGN_FLOAT = 0x109,
        ADDASSIGN_DOUBLE = 0x10A,
        SUBASSIGN_INT = 0x10B,
        SUBASSIGN_UINT = 0x10C,
        SUBASSIGN_LONG = 0x10D,
        SUBASSIGN_ULONG = 0x10E,
        ASSIGN = 0x10F,
        SUBASSIGN_FLOAT = 0x110,
        SUBASSIGN_DOUBLE = 0x111,
        MULTASSIGN_INT = 0x112,
        MULTASSIGN_UINT = 0x113,
        MULTASSIGN_LONG = 0x114,
        MULTASSIGN_ULONG = 0x115,
        MULTASSIGN_DEC = 0x116,
        MULTASSIGN_FLOAT = 0x117,
        MULTASSIGN_DOUBLE = 0x118,
        DUP_STACKED_LVALUE = 0x119,
        EQ_ARRAY = 0x11A,
        BEGIN_ASSIGN = 0x11B,
        CONV_TO_LVALUE = 0x11C,
        BEGIN_ASSIGN = 0x11D,
        PUSH_SHARED_VAR_LV = 0x11E,
        PUSH_LOCAL_GLOBREF_LV = 0x11F,
        PUSH_LOCAL_ARGREF_LV = 0x120,
        PUSH_SHARED_GLOBREF_LV = 0x121,
        DOT_LV = 0x122,
        INDEX_LV = 0x123,
        NOOP = 0x124,
        POP = 0x125,
        FREE = 0x126,
        PUSH_RESULT = 0x127,
        POP_POP = 0x128,
        POP_FREE = 0x129,
        FREE_POP = 0x12A,
        FREE_FREE = 0x12B,
        COPY_ARRAY_INSTANCE = 0x12C,
        COPY_STRUCTURE_INSTANCE = 0x12D,
        COPY_CONST_DOUBLE = 0x12E,
        COPY_CONST_DEC = 0x12F,
        COPY_CONST_DATE = 0x130,
        COPY_CONST_TIME = 0x131,
        COPY_CONST_DATETIME = 0x132,
        COPY_CONST_STRING = 0x133,
        COPY_LVALUE_DOUBLE = 0x134,
        COPY_LVALUE_DEC = 0x135,
        COPY_LVALUE_DATE = 0x136,
        COPY_LVALUE_TIME = 0x137,
        COPY_LVALUE_DATETIME = 0x138,
        COPY_LVALUE_STRING = 0x139,
        COPY_LVALUE_BINARY = 0x13A,
        POP_N_TIMES = 0x13B,
        FREE_NODE_N = 0x13C,
        CONV_DBL_RVALUE_TO_PTR = 0x13D,
        COPY_EXPR_DOUBLE = 0x13E,
        BREAKPOINT = 0x13F,
        INDEX_ERR_CHK = 0x140,
        DOT_DOUBLE = 0x141,
        DOT_DEC = 0x142,
        INDEX_DOUBLE = 0x143,
        INDEX_DEC = 0x144,
        INDEX_ERR_CHK_DBL = 0x145,
        INDEX_ERR_CHK_DEC = 0x146,
        GLOBFUNCCALL_DOUBLE = 0x147,
        GLOBFUNCCALL_DEC = 0x148,
        SYSFUNCCALL_DOUBLE = 0x149,
        SYSFUNCCALL_DEC = 0x14A,
        DLLFUNCCALL_DOUBLE = 0x14B,
        CALL_FUNCTION = 0x14C,
        DOTFUNCCALL_DOUBLE = 0x14D,
        DOTFUNCCALL_DEC = 0x14E,
        PUSH_LOCAL_VAR_DOUBLE = 0x14F,
        PUSH_LOCAL_VAR_DEC = 0x150,
        PUSH_SHARED_VAR_DOUBLE = 0x151,
        PUSH_SHARED_VAR_DEC = 0x152,
        PUSH_LOCAL_GLOBREF_DOUBLE = 0x153,
        PUSH_LOCAL_GLOBREF_DEC = 0x154,
        PUSH_LOCAL_ARGREF_DOUBLE = 0x155,
        PUSH_LOCAL_ARGREF_DEC = 0x156,
        PUSH_SHARED_GLOBREF_DOUBLE = 0x157,
        PUSH_SHARED_GLOBREF_DEC = 0x158,
        ASSIGN_ANY = 0x159,
        CNV_ANY_TO_INT = 0x15A,
        CNV_ANY_TO_UINT = 0x15B,
        CNV_ANY_TO_LONG = 0x15C,
        CNV_ANY_TO_ULONG = 0x15D,
        CNV_ANY_TO_DEC = 0x15E,
        CNV_ANY_TO_FLOAT = 0x15F,
        CNV_ANY_TO_DOUBLE = 0x160,
        CNV_ANY_TO_STRING = 0x161,
        CNV_ANY_TO_BOOL = 0x162,
        CNV_ANY_TO_BINARY = 0x163,
        CNV_ANY_TO_DATE = 0x164,
        CNV_ANY_TO_TIME = 0x165,
        CNV_ANY_TO_DATETIME = 0x166,
        CNV_ANY_TO_CHAR = 0x167,
        CNV_ANY_TO_HANDLE = 0x168,
        CNV_ANY_TO_ENUM = 0x169,
        CNV_ANY_TO_OBJECT = 0x16A,
        CONV_DEC_RVALUE_TO_PTR = 0x16B,
        COPY_EXPR_DEC = 0x16C,
        CREATE_EXT_OBJ = 0x16D,
        GLOBFUNCCALL_ANY = 0x16E,
        SYSFUNCCALL_ANY = 0x16F,
        DLLFUNCCALL_ANY = 0x170,
        DOTFUNCCALL_ANY = 0x171,
        PUSH_LOCAL_VAR_ANY = 0x172,
        PUSH_SHARED_VAR_ANY = 0x173,
        PUSH_LOCAL_GLOBREF_ANY = 0x174,
        PUSH_LOCAL_ARGREF_ANY = 0x175,
        PUSH_SHARED_GLOBREF_ANY = 0x176,
        ADD_ANY = 0x177,
        SUB_ANY = 0x178,
        MULT_ANY = 0x179,
        DIV_ANY = 0x17A,
        EQ = 0x17B,
        NEGATE_ANY = 0x17C,
        EQ_ANY = 0x17D,
        NE_ANY = 0x17E,
        GT_ANY = 0x17F,
        LT_ANY = 0x180,
        GE_ANY = 0x181,
        LE_ANY = 0x182,
        AND_ANY = 0x183,
        OR_ANY = 0x184,
        NOT_ANY = 0x185,
        DOT_ANY = 0x186,
        INDEX_ANY = 0x187,
        INDEX_ERR_CHK_ANY = 0x188,
        INT = 0x189,
        ABS_LONG = 0x18A,
        ABS_DOUBLE = 0x18B,
        ASC = 0x18C,
        BLOB = 0x18D,
        CEILING = 0x18E,
        COS = 0x18F,
        EXP = 0x190,
        FACT = 0x191,
        INTHIGH = 0x192,
        INTLOW = 0x193,
        ISDATE = 0x194,
        ISNULL = 0x195,
        ISNUMBER = 0x196,
        ISTIME = 0x197,
        ISVALID = 0x198,
        LEN_STRING = 0x199,
        LEN_BINARY = 0x19A,
        LOG = 0x19B,
        LOGTEN = 0x19C,
        LOWER = 0x19D,
        PI = 0x19E,
        RAND_LONG = 0x19F,
        RAND_DOUBLE = 0x1A0,
        SIN = 0x1A1,
        SQRT = 0x1A2,
        TAN = 0x1A3,
        UPPER = 0x1A4,
        CONV_TO_REFPAK = 0x1A5,
        PUSH_LOCAL_GLOBREF_RP = 0x1A6,
        PUSH_LOCAL_ARGREF_RP = 0x1A7,
        PUSH_SHARED_GLOBREF_RP = 0x1A8,
        PUSH_LOCAL_VAR_RP = 0x1A9,
        PUSH_LOCAL_VAR = 0x1AA,
        PUSH_SHARED_VAR = 0x1AB,
        TRANSFORM_BOUNDED_TO_UNBOUNDED = 0x1AC,
        TRANSFORM_UNBOUNDED_TO_BOUNDED = 0x1AD,
        TRANSFORM_UNBOUNDED_TO_UNBOUNDED = 0x1AE,
        CALC_UNBOUNDED_ARRAY_BOUND = 0x1AF,
        CALC_SIMPLE_ARRAY_BOUND = 0x1B0,
        CALC_COMPLEX_ARRAY_BOUND = 0x1B1,
        BUILD_UNBOUNDED_ARRAYLIST = 0x1B2,
        BUILD_BOUNDED_ARRAYLIST = 0x1B3,
        TRANSFORM_ARRAYLIST_TO_UNBOUNDED = 0x1B4,
        TRANSFORM_ARRAYLIST_TO_BOUNDED = 0x1B5,
        FREE_REF_PAK_N = 0x1B6,
        ARRAY_BOUND_INFO = 0x1B7,
        LOWERBOUND = 0x1B8,
        UPPERBOUND = 0x1B9,
        INCR_ANY = 0x1BA,
        DECR_ANY = 0x1BB,
        PUSH_FUNC_CLASS = 0x1BC,
        CLASS_CALL = 0x1BD,
        CLASS_CALL_DEC = 0x1BE,
        CLASS_CALL_DOUBLE = 0x1BF,
        CLASS_CALL_ANY = 0x1C0,
        INDEX_RP = 0x1C1,
        DBDELETEWITHCURS = 0x1C2,
        DBEXECUTEIMMED = 0x1C3,
        DBEXECDYNWITHDESC = 0x1C4,
        DBFETCHWITHDESC = 0x1C5,
        DBOPENDYNWITHDESC = 0x1C6,
        DBUPDATEWITHCURS = 0x1C7,
        CREATE_USING = 0x1C8,
        TRANSFORM_ANY_TO_UNBOUNDED = 0x1C9,
        TRANSFORM_ANY_TO_BOUNDED = 0x1CA,
        FREE_INV_METH_ARGS = 0x1CB,
        PUSH_NULL = 0x1CC,
        COPY_LVALUE_ANY = 0x1CD,
        ENTER_EMBEDDED = 0x1CE,
        EXIT_EMBEDDED = 0x1CF,
        DOT_FLD_UPDATE_INDEX_RP = 0x1D0,
        CNV_STRING_TO_BOUNDED_CHARARRAY = 0x1D1,
        PUSH_NTH_PARENT = 0x1D2,
        MOD_LONG = 0x1D3,
        MOD_ULONG = 0x1D4,
        MOD_DOUBLE = 0x1D5,
        MOD_DEC = 0x1D6,
        MOD_ANY = 0x1D7,
        ABS_DEC = 0x1D8,
        ABS_ANY = 0x1D9,
        CEILING_ANY = 0x1DA,
        MIN_LONG = 0x1DB,
        MIN_ULONG = 0x1DC,
        MIN_DOUBLE = 0x1DD,
        MIN_DEC = 0x1DE,
        MIN_ANY = 0x1DF,
        MAX_LONG = 0x1E0,
        MAX_ULONG = 0x1E1,
        MAX_DOUBLE = 0x1E2,
        MAX_DEC = 0x1E3,
        MAX_ANY = 0x1E4,
        PUSH_TRY = 0x1E5,
        POP_TRY = 0x1E6,
        CATCH_EXCEPTION = 0x1E7,
        THROW_EXCEPTION = 0x1E8,
        GOSUB = 0x1E9,
        RETURN_SUB = 0x1EA,
        CNV_INT_TO_LONGLONG = 0x1EB,
        CNV_UINT_TO_LONGLONG = 0x1EC,
        CNV_LONG_TO_LONGLONG = 0x1ED,
        CNV_ULONG_TO_LONGLONG = 0x1EE,
        CNV_DEC_TO_LONGLONG = 0x1EF,
        CNV_FLOAT_TO_LONGLONG = 0x1F0,
        CNV_DOUBLE_TO_LONGLONG = 0x1F1,
        CNV_LONGLONG_TO_INT = 0x1F2,
        CNV_LONGLONG_TO_UINT = 0x1F3,
        CNV_LONGLONG_TO_LONG = 0x1F4,
        CNV_LONGLONG_TO_ULONG = 0x1F5,
        CNV_LONGLONG_TO_DEC = 0x1F6,
        CNV_LONGLONG_TO_FLOAT = 0x1F7,
        CNV_LONGLONG_TO_DOUBLE = 0x1F8,
        ADD_LONGLONG = 0x1F9,
        ADD = 0x1FA,
        SUB = 0x1FB,
        DIV_LONGLONG = 0x1FC,
        POWER_LONGLONG = 0x1FD,
        POWER = 0x1FE,
        NEGATE = 0x1FF,
        PUSH_LOCAL_VAR_LONGLONG = 0x200,
        PUSH_LOCAL_GLOBREF_LONGLONG = 0x201,
        PUSH_LOCAL_ARGREF_LONGLONG = 0x202,
        PUSH_SHARED_VAR_LONGLONG = 0x203,
        PUSH_SHARED_GLOBREF_LONGLONG = 0x204,
        ASSIGN_LONGLONG = 0x205,
        COPY_CONST_LONGLONG = 0x206,
        ADDASSIGN_LONGLONG = 0x207,
        SUBASSIGN_LONGLONG = 0x208,
        MULTASSIGN_LONGLONG = 0x209,
        ASSIGN = 0x20A,
        DECR_LONGLONG = 0x20B,
        COPY_LVALUE_LONGLONG = 0x20C,
        ABS_LONGLONG = 0x20D,
        RAND_LONGLONG = 0x20E,
        EQ_LONGLONG = 0x20F,
        NE_LONGLONG = 0x210,
        GT_LONGLONG = 0x211,
        LT_LONGLONG = 0x212,
        GE_LONGLONG = 0x213,
        LE_LONGLONG = 0x214,
        MOD_LONGLONG = 0x215,
        MIN_LONGLONG = 0x216,
        MAX_LONGLONG = 0x217,
        GLOBFUNCCALL_LONGLONG = 0x218,
        SYSFUNCCALL_LONGLONG = 0x219,
        DLLFUNCCALL_LONGLONG = 0x21A,
        DOTFUNCCALL_LONGLONG = 0x21B,
        CALL_FUNCTION = 0x21C,
        COPY_EXPR_LONGLONG = 0x21D,
        DOT_LONGLONG = 0x21E,
        INDEX_LONGLONG = 0x21F,
        CNV_ANY_TO_LONGLONG = 0x220,
        CONV_LONGLONG_RVALUE_TO_PTR = 0x221,
        INDEX_ERR_CHK_LONGLONG = 0x222,
        PUSH_CONST_BYTE = 0x223,
        CNV_INT_TO_BYTE = 0x224,
        CNV_UINT_TO_BYTE = 0x225,
        CNV_LONG_TO_BYTE = 0x226,
        CNV_ULONG_TO_BYTE = 0x227,
        CNV_DEC_TO_BYTE = 0x228,
        CNV_FLOAT_TO_BYTE = 0x229,
        CNV_DOUBLE_TO_BYTE = 0x22A,
        CNV_ANY_TO_BYTE = 0x22B,
        CNV_LONGLONG_TO_BYTE = 0x22C,
        CNV_BYTE_TO_INT = 0x22D,
        CNV_BYTE_TO_UINT = 0x22E,
        CNV_BYTE_TO_LONG = 0x22F,
        CNV_BYTE_TO_ULONG = 0x230,
        CNV_BYTE_TO_DEC = 0x231,
        CNV_BYTE_TO_FLOAT = 0x232,
        CNV_BYTE_TO_DOUBLE = 0x233,
        CNV_BYTE_TO_LONGLONG = 0x234,
        ADD_BYTE = 0x235,
        SUB_BYTE = 0x236,
        MULT_BYTE = 0x237,
        DIV_BYTE = 0x238,
        POWER_BYTE = 0x239,
        NEGATE_BYTE = 0x23A,
        INCR_BYTE = 0x23B,
        DECR_BYTE = 0x23C,
        ASSIGN_BYTE = 0x23D,
        ADDASSIGN_BYTE = 0x23E,
        SUBASSIGN_BYTE = 0x23F,
        MULTASSIGN_BYTE = 0x240,
        EQ_BYTE = 0x241,
        NE_BYTE = 0x242,
        GT_BYTE = 0x243,
        LT_BYTE = 0x244,
        GE_BYTE = 0x245,
        LE_BYTE = 0x246,
    }

    public class OpcodeInfo
    {
        public ushort Opcode { get; set; }
        public string Name { get; set; }
        public byte Length { get; set; }
        public string Category { get; set; }
        public string StackEffect { get; set; }

        private static readonly Dictionary<ushort, OpcodeInfo> _opcodes = new()
        {
            { 0x00, new OpcodeInfo { Opcode = 0x00, Name = "RETURN", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x01, new OpcodeInfo { Opcode = 0x01, Name = "STORE_RETURN_VAL", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x02, new OpcodeInfo { Opcode = 0x02, Name = "JUMPTRUE", Length = 2, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x03, new OpcodeInfo { Opcode = 0x03, Name = "JUMPFALSE", Length = 2, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x04, new OpcodeInfo { Opcode = 0x04, Name = "JUMP", Length = 2, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x05, new OpcodeInfo { Opcode = 0x05, Name = "DBSTART", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x06, new OpcodeInfo { Opcode = 0x06, Name = "DBCOMMIT", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x07, new OpcodeInfo { Opcode = 0x07, Name = "DBROLLBACK", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x08, new OpcodeInfo { Opcode = 0x08, Name = "DBSTOP", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x09, new OpcodeInfo { Opcode = 0x09, Name = "DBCLOSE", Length = 1, Category = "sm", StackEffect = "3 -> 0" } },
            { 0x0A, new OpcodeInfo { Opcode = 0x0A, Name = "DBOPEN", Length = 2, Category = "sm", StackEffect = "3 -> 0" } },
            { 0x0B, new OpcodeInfo { Opcode = 0x0B, Name = "DBDELETE", Length = 4, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x0C, new OpcodeInfo { Opcode = 0x0C, Name = "DBUPDATE", Length = 4, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x0D, new OpcodeInfo { Opcode = 0x0D, Name = "DBEXECUTE", Length = 2, Category = "sm", StackEffect = "" } },
            { 0x0E, new OpcodeInfo { Opcode = 0x0E, Name = "DBFETCH", Length = 4, Category = "sm", StackEffect = "3 -> 0" } },
            { 0x0F, new OpcodeInfo { Opcode = 0x0F, Name = "DBINSERT", Length = 4, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x10, new OpcodeInfo { Opcode = 0x10, Name = "DBSELECT", Length = 5, Category = "sm", StackEffect = "3 -> 0" } },
            { 0x11, new OpcodeInfo { Opcode = 0x11, Name = "DESTROY", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x12, new OpcodeInfo { Opcode = 0x12, Name = "HALT", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x13, new OpcodeInfo { Opcode = 0x13, Name = "EVENTCALL", Length = 6, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x14, new OpcodeInfo { Opcode = 0x14, Name = "LVALUE_EXPR", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x15, new OpcodeInfo { Opcode = 0x15, Name = "DBEXECUTEDYN", Length = 4, Category = "sm", StackEffect = "" } },
            { 0x16, new OpcodeInfo { Opcode = 0x16, Name = "DBPREPARE", Length = 1, Category = "sm", StackEffect = "5 -> 0" } },
            { 0x17, new OpcodeInfo { Opcode = 0x17, Name = "DBOPENDYN", Length = 4, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x18, new OpcodeInfo { Opcode = 0x18, Name = "DBEXECDYNPROC", Length = 4, Category = "sm", StackEffect = "" } },
            { 0x19, new OpcodeInfo { Opcode = 0x19, Name = "DBDESCRIBE", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1A, new OpcodeInfo { Opcode = 0x1A, Name = "DBSELECTBLOB", Length = 5, Category = "sm", StackEffect = "3 -> 0" } },
            { 0x1B, new OpcodeInfo { Opcode = 0x1B, Name = "DBUPDATEBLOB", Length = 4, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x1C, new OpcodeInfo { Opcode = 0x1C, Name = "DBSELECTCLOB", Length = 6, Category = "sm", StackEffect = "3 -> 0" } },
            { 0x1D, new OpcodeInfo { Opcode = 0x1D, Name = "DBUPDATECLOB", Length = 5, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x1E, new OpcodeInfo { Opcode = 0x1E, Name = "PUSH_LOCAL_VAR", Length = 2, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x1F, new OpcodeInfo { Opcode = 0x1F, Name = "PUSH_SHARED_VAR", Length = 2, Category = "sm", StackEffect = "" } },
            { 0x20, new OpcodeInfo { Opcode = 0x20, Name = "PUSH_CONST_REF", Length = 3, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x21, new OpcodeInfo { Opcode = 0x21, Name = "PUSH_THIS", Length = 1, Category = "sm", StackEffect = "0 -> 1" } },
            { 0x22, new OpcodeInfo { Opcode = 0x22, Name = "PUSH_PARENT", Length = 1, Category = "sm", StackEffect = "0 -> 1" } },
            { 0x23, new OpcodeInfo { Opcode = 0x23, Name = "PUSH_PRIMARY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x24, new OpcodeInfo { Opcode = 0x24, Name = "AND", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x25, new OpcodeInfo { Opcode = 0x25, Name = "OR", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x26, new OpcodeInfo { Opcode = 0x26, Name = "NOT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x27, new OpcodeInfo { Opcode = 0x27, Name = "DOT", Length = 2, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x28, new OpcodeInfo { Opcode = 0x28, Name = "INDEX", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x29, new OpcodeInfo { Opcode = 0x29, Name = "GLOBFUNCCALL", Length = 3, Category = "sm", StackEffect = "" } },
            { 0x2A, new OpcodeInfo { Opcode = 0x2A, Name = "CALL_FUNCTION", Length = 2, Category = "sm", StackEffect = "" } },
            { 0x2B, new OpcodeInfo { Opcode = 0x2B, Name = "DLLFUNCCALL", Length = 3, Category = "sm", StackEffect = "" } },
            { 0x2C, new OpcodeInfo { Opcode = 0x2C, Name = "DOTFUNCCALL", Length = 3, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x2D, new OpcodeInfo { Opcode = 0x2D, Name = "PUSH_GLOBAL_VAR", Length = 3, Category = "sm", StackEffect = "0 -> 1" } },
            { 0x2E, new OpcodeInfo { Opcode = 0x2E, Name = "ARRAYLIST", Length = 3, Category = "sm", StackEffect = "" } },
            { 0x2F, new OpcodeInfo { Opcode = 0x2F, Name = "PUSH_SHARED_VAR", Length = 2, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x30, new OpcodeInfo { Opcode = 0x30, Name = "PUSH_LOCAL_ARGREF", Length = 2, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x31, new OpcodeInfo { Opcode = 0x31, Name = "PUSH_SHARED_GLOBREF", Length = 2, Category = "sm", StackEffect = "" } },
            { 0x32, new OpcodeInfo { Opcode = 0x32, Name = "PUSH_CONST_INT", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x33, new OpcodeInfo { Opcode = 0x33, Name = "PUSH_CONST_UINT", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x34, new OpcodeInfo { Opcode = 0x34, Name = "PUSH_CONST_LONG", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x35, new OpcodeInfo { Opcode = 0x35, Name = "PUSH_CONST_ULONG", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x36, new OpcodeInfo { Opcode = 0x36, Name = "PUSH_CONST_DEC", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x37, new OpcodeInfo { Opcode = 0x37, Name = "PUSH_CONST_FLOAT", Length = 2, Category = "sm", StackEffect = "" } },
            { 0x38, new OpcodeInfo { Opcode = 0x38, Name = "PUSH_CONST_DOUBLE", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x39, new OpcodeInfo { Opcode = 0x39, Name = "PUSH_CONST_TIME", Length = 2, Category = "sm", StackEffect = "" } },
            { 0x3A, new OpcodeInfo { Opcode = 0x3A, Name = "PUSH_CONST_DATE", Length = 2, Category = "sm", StackEffect = "" } },
            { 0x3B, new OpcodeInfo { Opcode = 0x3B, Name = "PUSH_CONST_STRING", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x3C, new OpcodeInfo { Opcode = 0x3C, Name = "PUSH_CONST_BOOL", Length = 2, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x3D, new OpcodeInfo { Opcode = 0x3D, Name = "PUSH_CONST_ENUM", Length = 2, Category = "sm", StackEffect = "0 -> 1" } },
            { 0x3E, new OpcodeInfo { Opcode = 0x3E, Name = "CNV_INT_TO_UINT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x3F, new OpcodeInfo { Opcode = 0x3F, Name = "CNV_INT_TO_LONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x40, new OpcodeInfo { Opcode = 0x40, Name = "CNV_INT_TO_ULONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x41, new OpcodeInfo { Opcode = 0x41, Name = "CNV_INT_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x42, new OpcodeInfo { Opcode = 0x42, Name = "CNV_INT_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x43, new OpcodeInfo { Opcode = 0x43, Name = "CNV_INT_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x44, new OpcodeInfo { Opcode = 0x44, Name = "CNV_UINT_TO_LONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x45, new OpcodeInfo { Opcode = 0x45, Name = "CNV_UINT_TO_ULONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x46, new OpcodeInfo { Opcode = 0x46, Name = "CNV_UINT_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x47, new OpcodeInfo { Opcode = 0x47, Name = "CNV_UINT_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x48, new OpcodeInfo { Opcode = 0x48, Name = "CNV_UINT_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x49, new OpcodeInfo { Opcode = 0x49, Name = "CNV_LONG_TO_ULONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x4A, new OpcodeInfo { Opcode = 0x4A, Name = "CNV_LONG_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x4B, new OpcodeInfo { Opcode = 0x4B, Name = "CNV_LONG_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x4C, new OpcodeInfo { Opcode = 0x4C, Name = "CNV_LONG_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x4D, new OpcodeInfo { Opcode = 0x4D, Name = "CNV_ULONG_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x4E, new OpcodeInfo { Opcode = 0x4E, Name = "CNV_ULONG_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x4F, new OpcodeInfo { Opcode = 0x4F, Name = "CNV_ULONG_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x50, new OpcodeInfo { Opcode = 0x50, Name = "CNV_DEC_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x51, new OpcodeInfo { Opcode = 0x51, Name = "CNV_DEC_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x52, new OpcodeInfo { Opcode = 0x52, Name = "CNV_FLOAT_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x53, new OpcodeInfo { Opcode = 0x53, Name = "ADD_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x54, new OpcodeInfo { Opcode = 0x54, Name = "ADD_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x55, new OpcodeInfo { Opcode = 0x55, Name = "ADD_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x56, new OpcodeInfo { Opcode = 0x56, Name = "ADD_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x57, new OpcodeInfo { Opcode = 0x57, Name = "ADD_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x58, new OpcodeInfo { Opcode = 0x58, Name = "ADD_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x59, new OpcodeInfo { Opcode = 0x59, Name = "ADD_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x5A, new OpcodeInfo { Opcode = 0x5A, Name = "SUB_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x5B, new OpcodeInfo { Opcode = 0x5B, Name = "SUB_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x5C, new OpcodeInfo { Opcode = 0x5C, Name = "SUB_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x5D, new OpcodeInfo { Opcode = 0x5D, Name = "SUB_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x5E, new OpcodeInfo { Opcode = 0x5E, Name = "SUB", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x5F, new OpcodeInfo { Opcode = 0x5F, Name = "SUB_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x60, new OpcodeInfo { Opcode = 0x60, Name = "SUB_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x61, new OpcodeInfo { Opcode = 0x61, Name = "MULT_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x62, new OpcodeInfo { Opcode = 0x62, Name = "MULT_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x63, new OpcodeInfo { Opcode = 0x63, Name = "MULT_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x64, new OpcodeInfo { Opcode = 0x64, Name = "MULT_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x65, new OpcodeInfo { Opcode = 0x65, Name = "MULT_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x66, new OpcodeInfo { Opcode = 0x66, Name = "MULT_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x67, new OpcodeInfo { Opcode = 0x67, Name = "MULT_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x68, new OpcodeInfo { Opcode = 0x68, Name = "DIV_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x69, new OpcodeInfo { Opcode = 0x69, Name = "DIV_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x6A, new OpcodeInfo { Opcode = 0x6A, Name = "DIV_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x6B, new OpcodeInfo { Opcode = 0x6B, Name = "DIV_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x6C, new OpcodeInfo { Opcode = 0x6C, Name = "DIV", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x6D, new OpcodeInfo { Opcode = 0x6D, Name = "DIV_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x6E, new OpcodeInfo { Opcode = 0x6E, Name = "DIV_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x6F, new OpcodeInfo { Opcode = 0x6F, Name = "POWER_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x70, new OpcodeInfo { Opcode = 0x70, Name = "POWER_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x71, new OpcodeInfo { Opcode = 0x71, Name = "POWER_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x72, new OpcodeInfo { Opcode = 0x72, Name = "POWER_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x73, new OpcodeInfo { Opcode = 0x73, Name = "POWER_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x74, new OpcodeInfo { Opcode = 0x74, Name = "POWER_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x75, new OpcodeInfo { Opcode = 0x75, Name = "POWER_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x76, new OpcodeInfo { Opcode = 0x76, Name = "NEGATE_INT", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x77, new OpcodeInfo { Opcode = 0x77, Name = "NEGATE_UINT", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x78, new OpcodeInfo { Opcode = 0x78, Name = "NEGATE_LONG", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x79, new OpcodeInfo { Opcode = 0x79, Name = "NEGATE_ULONG", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x7A, new OpcodeInfo { Opcode = 0x7A, Name = "NEGATE_DEC", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x7B, new OpcodeInfo { Opcode = 0x7B, Name = "NEGATE_FLOAT", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x7C, new OpcodeInfo { Opcode = 0x7C, Name = "ADD", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x7D, new OpcodeInfo { Opcode = 0x7D, Name = "CAT_STRING", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x7E, new OpcodeInfo { Opcode = 0x7E, Name = "CAT_BINARY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x7F, new OpcodeInfo { Opcode = 0x7F, Name = "ASSIGN_ARRAY", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x80, new OpcodeInfo { Opcode = 0x80, Name = "ASSIGN_INT", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x81, new OpcodeInfo { Opcode = 0x81, Name = "ASSIGN_UINT", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x82, new OpcodeInfo { Opcode = 0x82, Name = "ASSIGN_LONG", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x83, new OpcodeInfo { Opcode = 0x83, Name = "ASSIGN_ULONG", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x84, new OpcodeInfo { Opcode = 0x84, Name = "ASSIGN_DEC", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x85, new OpcodeInfo { Opcode = 0x85, Name = "ASSIGN_FLOAT", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x86, new OpcodeInfo { Opcode = 0x86, Name = "ASSIGN_DOUBLE", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x87, new OpcodeInfo { Opcode = 0x87, Name = "ASSIGN_BLOB", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x88, new OpcodeInfo { Opcode = 0x88, Name = "ASSIGN_STRING", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x89, new OpcodeInfo { Opcode = 0x89, Name = "ASSIGN_TIME", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x8A, new OpcodeInfo { Opcode = 0x8A, Name = "ASSIGN_OBINST", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x8B, new OpcodeInfo { Opcode = 0x8B, Name = "ASSIGN_ANCESTOR", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x8C, new OpcodeInfo { Opcode = 0x8C, Name = "ASSIGN_ENUM", Length = 2, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x8D, new OpcodeInfo { Opcode = 0x8D, Name = "CNV_UINT_TO_INT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x8E, new OpcodeInfo { Opcode = 0x8E, Name = "CNV_LONG_TO_INT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x8F, new OpcodeInfo { Opcode = 0x8F, Name = "CNV_ULONG_TO_INT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x90, new OpcodeInfo { Opcode = 0x90, Name = "CNV_DEC_TO_INT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x91, new OpcodeInfo { Opcode = 0x91, Name = "CNV_FLOAT_TO_INT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x92, new OpcodeInfo { Opcode = 0x92, Name = "CNV_DOUBLE_TO_INT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x93, new OpcodeInfo { Opcode = 0x93, Name = "CNV_LONG_TO_UINT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x94, new OpcodeInfo { Opcode = 0x94, Name = "CNV_ULONG_TO_UINT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x95, new OpcodeInfo { Opcode = 0x95, Name = "CNV_DEC_TO_UINT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x96, new OpcodeInfo { Opcode = 0x96, Name = "CNV_FLOAT_TO_UINT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x97, new OpcodeInfo { Opcode = 0x97, Name = "CNV_DOUBLE_TO_UINT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x98, new OpcodeInfo { Opcode = 0x98, Name = "CNV_ULONG_TO_LONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x99, new OpcodeInfo { Opcode = 0x99, Name = "CNV_DEC_TO_LONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x9A, new OpcodeInfo { Opcode = 0x9A, Name = "CNV_FLOAT_TO_LONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x9B, new OpcodeInfo { Opcode = 0x9B, Name = "CNV_DOUBLE_TO_LONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x9C, new OpcodeInfo { Opcode = 0x9C, Name = "CNV_DEC_TO_ULONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x9D, new OpcodeInfo { Opcode = 0x9D, Name = "CNV_FLOAT_TO_ULONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x9E, new OpcodeInfo { Opcode = 0x9E, Name = "CNV_DOUBLE_TO_ULONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x9F, new OpcodeInfo { Opcode = 0x9F, Name = "CNV_FLOAT_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0xA0, new OpcodeInfo { Opcode = 0xA0, Name = "CNV_DOUBLE_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0xA1, new OpcodeInfo { Opcode = 0xA1, Name = "CNV_DOUBLE_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0xA2, new OpcodeInfo { Opcode = 0xA2, Name = "CNV_STRING_TO_CHAR", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0xA3, new OpcodeInfo { Opcode = 0xA3, Name = "CNV_CHAR_TO_STRING", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0xA4, new OpcodeInfo { Opcode = 0xA4, Name = "CNV_STRING_TO_CHARARRAY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0xA5, new OpcodeInfo { Opcode = 0xA5, Name = "CNV_CHARARRAY_TO_STRING", Length = 1, Category = "sm", StackEffect = "" } },
            { 0xA6, new OpcodeInfo { Opcode = 0xA6, Name = "EQ_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xA7, new OpcodeInfo { Opcode = 0xA7, Name = "EQ_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xA8, new OpcodeInfo { Opcode = 0xA8, Name = "EQ_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xA9, new OpcodeInfo { Opcode = 0xA9, Name = "EQ_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xAA, new OpcodeInfo { Opcode = 0xAA, Name = "EQ_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xAB, new OpcodeInfo { Opcode = 0xAB, Name = "EQ_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xAC, new OpcodeInfo { Opcode = 0xAC, Name = "EQ_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xAD, new OpcodeInfo { Opcode = 0xAD, Name = "EQ_STRING", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xAE, new OpcodeInfo { Opcode = 0xAE, Name = "EQ_BOOL", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xAF, new OpcodeInfo { Opcode = 0xAF, Name = "EQ_BINARY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB0, new OpcodeInfo { Opcode = 0xB0, Name = "EQ_TIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB1, new OpcodeInfo { Opcode = 0xB1, Name = "EQ_DATE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB2, new OpcodeInfo { Opcode = 0xB2, Name = "EQ_DATETIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB3, new OpcodeInfo { Opcode = 0xB3, Name = "EQ_CHAR", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB4, new OpcodeInfo { Opcode = 0xB4, Name = "EQ_OBINST", Length = 1, Category = "sm", StackEffect = "" } },
            { 0xB5, new OpcodeInfo { Opcode = 0xB5, Name = "EQ_ENUM", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB6, new OpcodeInfo { Opcode = 0xB6, Name = "NE_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB7, new OpcodeInfo { Opcode = 0xB7, Name = "NE_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB8, new OpcodeInfo { Opcode = 0xB8, Name = "NE_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xB9, new OpcodeInfo { Opcode = 0xB9, Name = "NE_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xBA, new OpcodeInfo { Opcode = 0xBA, Name = "NE_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xBB, new OpcodeInfo { Opcode = 0xBB, Name = "NE_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xBC, new OpcodeInfo { Opcode = 0xBC, Name = "NE_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xBD, new OpcodeInfo { Opcode = 0xBD, Name = "NE_STRING", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xBE, new OpcodeInfo { Opcode = 0xBE, Name = "NE_BOOL", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xBF, new OpcodeInfo { Opcode = 0xBF, Name = "NE_BINARY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC0, new OpcodeInfo { Opcode = 0xC0, Name = "NE_TIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC1, new OpcodeInfo { Opcode = 0xC1, Name = "NE_DATE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC2, new OpcodeInfo { Opcode = 0xC2, Name = "NE_DATETIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC3, new OpcodeInfo { Opcode = 0xC3, Name = "NE_CHAR", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC4, new OpcodeInfo { Opcode = 0xC4, Name = "NE_OBINST", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC5, new OpcodeInfo { Opcode = 0xC5, Name = "NE_ENUM", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC6, new OpcodeInfo { Opcode = 0xC6, Name = "GT_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC7, new OpcodeInfo { Opcode = 0xC7, Name = "GT_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC8, new OpcodeInfo { Opcode = 0xC8, Name = "GT_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xC9, new OpcodeInfo { Opcode = 0xC9, Name = "GT_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xCA, new OpcodeInfo { Opcode = 0xCA, Name = "GT_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xCB, new OpcodeInfo { Opcode = 0xCB, Name = "GT_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xCC, new OpcodeInfo { Opcode = 0xCC, Name = "GT_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xCD, new OpcodeInfo { Opcode = 0xCD, Name = "GT_STRING", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xCE, new OpcodeInfo { Opcode = 0xCE, Name = "GT_TIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xCF, new OpcodeInfo { Opcode = 0xCF, Name = "GT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD0, new OpcodeInfo { Opcode = 0xD0, Name = "GT_DATETIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD1, new OpcodeInfo { Opcode = 0xD1, Name = "GT_CHAR", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD2, new OpcodeInfo { Opcode = 0xD2, Name = "LT_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD3, new OpcodeInfo { Opcode = 0xD3, Name = "LT_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD4, new OpcodeInfo { Opcode = 0xD4, Name = "LT_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD5, new OpcodeInfo { Opcode = 0xD5, Name = "LT_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD6, new OpcodeInfo { Opcode = 0xD6, Name = "LT_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD7, new OpcodeInfo { Opcode = 0xD7, Name = "LT_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD8, new OpcodeInfo { Opcode = 0xD8, Name = "LT_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xD9, new OpcodeInfo { Opcode = 0xD9, Name = "LT_STRING", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xDA, new OpcodeInfo { Opcode = 0xDA, Name = "LT_TIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xDB, new OpcodeInfo { Opcode = 0xDB, Name = "LT_DATE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xDC, new OpcodeInfo { Opcode = 0xDC, Name = "LT_DATETIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xDD, new OpcodeInfo { Opcode = 0xDD, Name = "LT_CHAR", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xDE, new OpcodeInfo { Opcode = 0xDE, Name = "GE_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xDF, new OpcodeInfo { Opcode = 0xDF, Name = "GE_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE0, new OpcodeInfo { Opcode = 0xE0, Name = "GE_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE1, new OpcodeInfo { Opcode = 0xE1, Name = "GE_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE2, new OpcodeInfo { Opcode = 0xE2, Name = "GE_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE3, new OpcodeInfo { Opcode = 0xE3, Name = "GE_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE4, new OpcodeInfo { Opcode = 0xE4, Name = "GE_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE5, new OpcodeInfo { Opcode = 0xE5, Name = "GE_STRING", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE6, new OpcodeInfo { Opcode = 0xE6, Name = "GE_TIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE7, new OpcodeInfo { Opcode = 0xE7, Name = "GE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE8, new OpcodeInfo { Opcode = 0xE8, Name = "GE_DATETIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xE9, new OpcodeInfo { Opcode = 0xE9, Name = "GE_CHAR", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xEA, new OpcodeInfo { Opcode = 0xEA, Name = "LE_INT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xEB, new OpcodeInfo { Opcode = 0xEB, Name = "LE_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xEC, new OpcodeInfo { Opcode = 0xEC, Name = "LE_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xED, new OpcodeInfo { Opcode = 0xED, Name = "LE_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xEE, new OpcodeInfo { Opcode = 0xEE, Name = "LE_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xEF, new OpcodeInfo { Opcode = 0xEF, Name = "LE_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xF0, new OpcodeInfo { Opcode = 0xF0, Name = "LE_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xF1, new OpcodeInfo { Opcode = 0xF1, Name = "LE_STRING", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xF2, new OpcodeInfo { Opcode = 0xF2, Name = "LE_TIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xF3, new OpcodeInfo { Opcode = 0xF3, Name = "LE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xF4, new OpcodeInfo { Opcode = 0xF4, Name = "LE_DATETIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xF5, new OpcodeInfo { Opcode = 0xF5, Name = "LE_CHAR", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0xF6, new OpcodeInfo { Opcode = 0xF6, Name = "INCR_INT", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xF7, new OpcodeInfo { Opcode = 0xF7, Name = "INCR_UINT", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xF8, new OpcodeInfo { Opcode = 0xF8, Name = "INCR_LONG", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xF9, new OpcodeInfo { Opcode = 0xF9, Name = "INCR_ULONG", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xFA, new OpcodeInfo { Opcode = 0xFA, Name = "INCR_DEC", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xFB, new OpcodeInfo { Opcode = 0xFB, Name = "INCR_FLOAT", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xFC, new OpcodeInfo { Opcode = 0xFC, Name = "INCR_DOUBLE", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xFD, new OpcodeInfo { Opcode = 0xFD, Name = "DECR_INT", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xFE, new OpcodeInfo { Opcode = 0xFE, Name = "DECR_UINT", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0xFF, new OpcodeInfo { Opcode = 0xFF, Name = "DECR_LONG", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x100, new OpcodeInfo { Opcode = 0x100, Name = "DECR_ULONG", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x101, new OpcodeInfo { Opcode = 0x101, Name = "DECR_DEC", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x102, new OpcodeInfo { Opcode = 0x102, Name = "DECR_FLOAT", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x103, new OpcodeInfo { Opcode = 0x103, Name = "DECR_DOUBLE", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x104, new OpcodeInfo { Opcode = 0x104, Name = "ADDASSIGN_INT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x105, new OpcodeInfo { Opcode = 0x105, Name = "ADDASSIGN_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x106, new OpcodeInfo { Opcode = 0x106, Name = "ADDASSIGN_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x107, new OpcodeInfo { Opcode = 0x107, Name = "ADDASSIGN_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x108, new OpcodeInfo { Opcode = 0x108, Name = "ADDASSIGN_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x109, new OpcodeInfo { Opcode = 0x109, Name = "ADDASSIGN_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x10A, new OpcodeInfo { Opcode = 0x10A, Name = "ADDASSIGN_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x10B, new OpcodeInfo { Opcode = 0x10B, Name = "SUBASSIGN_INT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x10C, new OpcodeInfo { Opcode = 0x10C, Name = "SUBASSIGN_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x10D, new OpcodeInfo { Opcode = 0x10D, Name = "SUBASSIGN_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x10E, new OpcodeInfo { Opcode = 0x10E, Name = "SUBASSIGN_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x10F, new OpcodeInfo { Opcode = 0x10F, Name = "ASSIGN", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x110, new OpcodeInfo { Opcode = 0x110, Name = "SUBASSIGN_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x111, new OpcodeInfo { Opcode = 0x111, Name = "SUBASSIGN_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x112, new OpcodeInfo { Opcode = 0x112, Name = "MULTASSIGN_INT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x113, new OpcodeInfo { Opcode = 0x113, Name = "MULTASSIGN_UINT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x114, new OpcodeInfo { Opcode = 0x114, Name = "MULTASSIGN_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x115, new OpcodeInfo { Opcode = 0x115, Name = "MULTASSIGN_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x116, new OpcodeInfo { Opcode = 0x116, Name = "MULTASSIGN_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x117, new OpcodeInfo { Opcode = 0x117, Name = "MULTASSIGN_FLOAT", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x118, new OpcodeInfo { Opcode = 0x118, Name = "MULTASSIGN_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x119, new OpcodeInfo { Opcode = 0x119, Name = "DUP_STACKED_LVALUE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x11A, new OpcodeInfo { Opcode = 0x11A, Name = "EQ_ARRAY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x11B, new OpcodeInfo { Opcode = 0x11B, Name = "BEGIN_ASSIGN", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x11C, new OpcodeInfo { Opcode = 0x11C, Name = "CONV_TO_LVALUE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x11D, new OpcodeInfo { Opcode = 0x11D, Name = "BEGIN_ASSIGN", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x11E, new OpcodeInfo { Opcode = 0x11E, Name = "PUSH_SHARED_VAR_LV", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x11F, new OpcodeInfo { Opcode = 0x11F, Name = "PUSH_LOCAL_GLOBREF_LV", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x120, new OpcodeInfo { Opcode = 0x120, Name = "PUSH_LOCAL_ARGREF_LV", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x121, new OpcodeInfo { Opcode = 0x121, Name = "PUSH_SHARED_GLOBREF_LV", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x122, new OpcodeInfo { Opcode = 0x122, Name = "DOT_LV", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x123, new OpcodeInfo { Opcode = 0x123, Name = "INDEX_LV", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x124, new OpcodeInfo { Opcode = 0x124, Name = "NOOP", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x125, new OpcodeInfo { Opcode = 0x125, Name = "POP", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x126, new OpcodeInfo { Opcode = 0x126, Name = "FREE", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x127, new OpcodeInfo { Opcode = 0x127, Name = "PUSH_RESULT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x128, new OpcodeInfo { Opcode = 0x128, Name = "POP_POP", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x129, new OpcodeInfo { Opcode = 0x129, Name = "POP_FREE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x12A, new OpcodeInfo { Opcode = 0x12A, Name = "FREE_POP", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x12B, new OpcodeInfo { Opcode = 0x12B, Name = "FREE_FREE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x12C, new OpcodeInfo { Opcode = 0x12C, Name = "COPY_ARRAY_INSTANCE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x12D, new OpcodeInfo { Opcode = 0x12D, Name = "COPY_STRUCTURE_INSTANCE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x12E, new OpcodeInfo { Opcode = 0x12E, Name = "COPY_CONST_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x12F, new OpcodeInfo { Opcode = 0x12F, Name = "COPY_CONST_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x130, new OpcodeInfo { Opcode = 0x130, Name = "COPY_CONST_DATE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x131, new OpcodeInfo { Opcode = 0x131, Name = "COPY_CONST_TIME", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x132, new OpcodeInfo { Opcode = 0x132, Name = "COPY_CONST_DATETIME", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x133, new OpcodeInfo { Opcode = 0x133, Name = "COPY_CONST_STRING", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x134, new OpcodeInfo { Opcode = 0x134, Name = "COPY_LVALUE_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x135, new OpcodeInfo { Opcode = 0x135, Name = "COPY_LVALUE_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x136, new OpcodeInfo { Opcode = 0x136, Name = "COPY_LVALUE_DATE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x137, new OpcodeInfo { Opcode = 0x137, Name = "COPY_LVALUE_TIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x138, new OpcodeInfo { Opcode = 0x138, Name = "COPY_LVALUE_DATETIME", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x139, new OpcodeInfo { Opcode = 0x139, Name = "COPY_LVALUE_STRING", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x13A, new OpcodeInfo { Opcode = 0x13A, Name = "COPY_LVALUE_BINARY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x13B, new OpcodeInfo { Opcode = 0x13B, Name = "POP_N_TIMES", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x13C, new OpcodeInfo { Opcode = 0x13C, Name = "FREE_NODE_N", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x13D, new OpcodeInfo { Opcode = 0x13D, Name = "CONV_DBL_RVALUE_TO_PTR", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x13E, new OpcodeInfo { Opcode = 0x13E, Name = "COPY_EXPR_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x13F, new OpcodeInfo { Opcode = 0x13F, Name = "BREAKPOINT", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x140, new OpcodeInfo { Opcode = 0x140, Name = "INDEX_ERR_CHK", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x141, new OpcodeInfo { Opcode = 0x141, Name = "DOT_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x142, new OpcodeInfo { Opcode = 0x142, Name = "DOT_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x143, new OpcodeInfo { Opcode = 0x143, Name = "INDEX_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x144, new OpcodeInfo { Opcode = 0x144, Name = "INDEX_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x145, new OpcodeInfo { Opcode = 0x145, Name = "INDEX_ERR_CHK_DBL", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x146, new OpcodeInfo { Opcode = 0x146, Name = "INDEX_ERR_CHK_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x147, new OpcodeInfo { Opcode = 0x147, Name = "GLOBFUNCCALL_DOUBLE", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x148, new OpcodeInfo { Opcode = 0x148, Name = "GLOBFUNCCALL_DEC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x149, new OpcodeInfo { Opcode = 0x149, Name = "SYSFUNCCALL_DOUBLE", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x14A, new OpcodeInfo { Opcode = 0x14A, Name = "SYSFUNCCALL_DEC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x14B, new OpcodeInfo { Opcode = 0x14B, Name = "DLLFUNCCALL_DOUBLE", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x14C, new OpcodeInfo { Opcode = 0x14C, Name = "CALL_FUNCTION", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x14D, new OpcodeInfo { Opcode = 0x14D, Name = "DOTFUNCCALL_DOUBLE", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x14E, new OpcodeInfo { Opcode = 0x14E, Name = "DOTFUNCCALL_DEC", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x14F, new OpcodeInfo { Opcode = 0x14F, Name = "PUSH_LOCAL_VAR_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x150, new OpcodeInfo { Opcode = 0x150, Name = "PUSH_LOCAL_VAR_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x151, new OpcodeInfo { Opcode = 0x151, Name = "PUSH_SHARED_VAR_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x152, new OpcodeInfo { Opcode = 0x152, Name = "PUSH_SHARED_VAR_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x153, new OpcodeInfo { Opcode = 0x153, Name = "PUSH_LOCAL_GLOBREF_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x154, new OpcodeInfo { Opcode = 0x154, Name = "PUSH_LOCAL_GLOBREF_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x155, new OpcodeInfo { Opcode = 0x155, Name = "PUSH_LOCAL_ARGREF_DOUBLE", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x156, new OpcodeInfo { Opcode = 0x156, Name = "PUSH_LOCAL_ARGREF_DEC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x157, new OpcodeInfo { Opcode = 0x157, Name = "PUSH_SHARED_GLOBREF_DOUBLE", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x158, new OpcodeInfo { Opcode = 0x158, Name = "PUSH_SHARED_GLOBREF_DEC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x159, new OpcodeInfo { Opcode = 0x159, Name = "ASSIGN_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x15A, new OpcodeInfo { Opcode = 0x15A, Name = "CNV_ANY_TO_INT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x15B, new OpcodeInfo { Opcode = 0x15B, Name = "CNV_ANY_TO_UINT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x15C, new OpcodeInfo { Opcode = 0x15C, Name = "CNV_ANY_TO_LONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x15D, new OpcodeInfo { Opcode = 0x15D, Name = "CNV_ANY_TO_ULONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x15E, new OpcodeInfo { Opcode = 0x15E, Name = "CNV_ANY_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x15F, new OpcodeInfo { Opcode = 0x15F, Name = "CNV_ANY_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x160, new OpcodeInfo { Opcode = 0x160, Name = "CNV_ANY_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x161, new OpcodeInfo { Opcode = 0x161, Name = "CNV_ANY_TO_STRING", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x162, new OpcodeInfo { Opcode = 0x162, Name = "CNV_ANY_TO_BOOL", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x163, new OpcodeInfo { Opcode = 0x163, Name = "CNV_ANY_TO_BINARY", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x164, new OpcodeInfo { Opcode = 0x164, Name = "CNV_ANY_TO_DATE", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x165, new OpcodeInfo { Opcode = 0x165, Name = "CNV_ANY_TO_TIME", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x166, new OpcodeInfo { Opcode = 0x166, Name = "CNV_ANY_TO_DATETIME", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x167, new OpcodeInfo { Opcode = 0x167, Name = "CNV_ANY_TO_CHAR", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x168, new OpcodeInfo { Opcode = 0x168, Name = "CNV_ANY_TO_HANDLE", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x169, new OpcodeInfo { Opcode = 0x169, Name = "CNV_ANY_TO_ENUM", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x16A, new OpcodeInfo { Opcode = 0x16A, Name = "CNV_ANY_TO_OBJECT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x16B, new OpcodeInfo { Opcode = 0x16B, Name = "CONV_DEC_RVALUE_TO_PTR", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x16C, new OpcodeInfo { Opcode = 0x16C, Name = "COPY_EXPR_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x16D, new OpcodeInfo { Opcode = 0x16D, Name = "CREATE_EXT_OBJ", Length = 1, Category = "sm", StackEffect = "0 -> 1" } },
            { 0x16E, new OpcodeInfo { Opcode = 0x16E, Name = "GLOBFUNCCALL_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x16F, new OpcodeInfo { Opcode = 0x16F, Name = "SYSFUNCCALL_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x170, new OpcodeInfo { Opcode = 0x170, Name = "DLLFUNCCALL_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x171, new OpcodeInfo { Opcode = 0x171, Name = "DOTFUNCCALL_ANY", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x172, new OpcodeInfo { Opcode = 0x172, Name = "PUSH_LOCAL_VAR_ANY", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x173, new OpcodeInfo { Opcode = 0x173, Name = "PUSH_SHARED_VAR_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x174, new OpcodeInfo { Opcode = 0x174, Name = "PUSH_LOCAL_GLOBREF_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x175, new OpcodeInfo { Opcode = 0x175, Name = "PUSH_LOCAL_ARGREF_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x176, new OpcodeInfo { Opcode = 0x176, Name = "PUSH_SHARED_GLOBREF_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x177, new OpcodeInfo { Opcode = 0x177, Name = "ADD_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x178, new OpcodeInfo { Opcode = 0x178, Name = "SUB_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x179, new OpcodeInfo { Opcode = 0x179, Name = "MULT_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x17A, new OpcodeInfo { Opcode = 0x17A, Name = "DIV_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x17B, new OpcodeInfo { Opcode = 0x17B, Name = "EQ", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x17C, new OpcodeInfo { Opcode = 0x17C, Name = "NEGATE_ANY", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x17D, new OpcodeInfo { Opcode = 0x17D, Name = "EQ_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x17E, new OpcodeInfo { Opcode = 0x17E, Name = "NE_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x17F, new OpcodeInfo { Opcode = 0x17F, Name = "GT_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x180, new OpcodeInfo { Opcode = 0x180, Name = "LT_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x181, new OpcodeInfo { Opcode = 0x181, Name = "GE_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x182, new OpcodeInfo { Opcode = 0x182, Name = "LE_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x183, new OpcodeInfo { Opcode = 0x183, Name = "AND_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x184, new OpcodeInfo { Opcode = 0x184, Name = "OR_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x185, new OpcodeInfo { Opcode = 0x185, Name = "NOT_ANY", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x186, new OpcodeInfo { Opcode = 0x186, Name = "DOT_ANY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x187, new OpcodeInfo { Opcode = 0x187, Name = "INDEX_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x188, new OpcodeInfo { Opcode = 0x188, Name = "INDEX_ERR_CHK_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x189, new OpcodeInfo { Opcode = 0x189, Name = "INT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x18A, new OpcodeInfo { Opcode = 0x18A, Name = "ABS_LONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x18B, new OpcodeInfo { Opcode = 0x18B, Name = "ABS_DOUBLE", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x18C, new OpcodeInfo { Opcode = 0x18C, Name = "ASC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x18D, new OpcodeInfo { Opcode = 0x18D, Name = "BLOB", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x18E, new OpcodeInfo { Opcode = 0x18E, Name = "CEILING", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x18F, new OpcodeInfo { Opcode = 0x18F, Name = "COS", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x190, new OpcodeInfo { Opcode = 0x190, Name = "EXP", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x191, new OpcodeInfo { Opcode = 0x191, Name = "FACT", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x192, new OpcodeInfo { Opcode = 0x192, Name = "INTHIGH", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x193, new OpcodeInfo { Opcode = 0x193, Name = "INTLOW", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x194, new OpcodeInfo { Opcode = 0x194, Name = "ISDATE", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x195, new OpcodeInfo { Opcode = 0x195, Name = "ISNULL", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x196, new OpcodeInfo { Opcode = 0x196, Name = "ISNUMBER", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x197, new OpcodeInfo { Opcode = 0x197, Name = "ISTIME", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x198, new OpcodeInfo { Opcode = 0x198, Name = "ISVALID", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x199, new OpcodeInfo { Opcode = 0x199, Name = "LEN_STRING", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x19A, new OpcodeInfo { Opcode = 0x19A, Name = "LEN_BINARY", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x19B, new OpcodeInfo { Opcode = 0x19B, Name = "LOG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x19C, new OpcodeInfo { Opcode = 0x19C, Name = "LOGTEN", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x19D, new OpcodeInfo { Opcode = 0x19D, Name = "LOWER", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x19E, new OpcodeInfo { Opcode = 0x19E, Name = "PI", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x19F, new OpcodeInfo { Opcode = 0x19F, Name = "RAND_LONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1A0, new OpcodeInfo { Opcode = 0x1A0, Name = "RAND_DOUBLE", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1A1, new OpcodeInfo { Opcode = 0x1A1, Name = "SIN", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1A2, new OpcodeInfo { Opcode = 0x1A2, Name = "SQRT", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1A3, new OpcodeInfo { Opcode = 0x1A3, Name = "TAN", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1A4, new OpcodeInfo { Opcode = 0x1A4, Name = "UPPER", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1A5, new OpcodeInfo { Opcode = 0x1A5, Name = "CONV_TO_REFPAK", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1A6, new OpcodeInfo { Opcode = 0x1A6, Name = "PUSH_LOCAL_GLOBREF_RP", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x1A7, new OpcodeInfo { Opcode = 0x1A7, Name = "PUSH_LOCAL_ARGREF_RP", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1A8, new OpcodeInfo { Opcode = 0x1A8, Name = "PUSH_SHARED_GLOBREF_RP", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1A9, new OpcodeInfo { Opcode = 0x1A9, Name = "PUSH_LOCAL_VAR_RP", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x1AA, new OpcodeInfo { Opcode = 0x1AA, Name = "PUSH_LOCAL_VAR", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x1AB, new OpcodeInfo { Opcode = 0x1AB, Name = "PUSH_SHARED_VAR", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1AC, new OpcodeInfo { Opcode = 0x1AC, Name = "TRANSFORM_BOUNDED_TO_UNBOUNDED", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1AD, new OpcodeInfo { Opcode = 0x1AD, Name = "TRANSFORM_UNBOUNDED_TO_BOUNDED", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1AE, new OpcodeInfo { Opcode = 0x1AE, Name = "TRANSFORM_UNBOUNDED_TO_UNBOUNDED", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1AF, new OpcodeInfo { Opcode = 0x1AF, Name = "CALC_UNBOUNDED_ARRAY_BOUND", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1B0, new OpcodeInfo { Opcode = 0x1B0, Name = "CALC_SIMPLE_ARRAY_BOUND", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1B1, new OpcodeInfo { Opcode = 0x1B1, Name = "CALC_COMPLEX_ARRAY_BOUND", Length = 1, Category = "sm", StackEffect = "4 -> 1" } },
            { 0x1B2, new OpcodeInfo { Opcode = 0x1B2, Name = "BUILD_UNBOUNDED_ARRAYLIST", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1B3, new OpcodeInfo { Opcode = 0x1B3, Name = "BUILD_BOUNDED_ARRAYLIST", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1B4, new OpcodeInfo { Opcode = 0x1B4, Name = "TRANSFORM_ARRAYLIST_TO_UNBOUNDED", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1B5, new OpcodeInfo { Opcode = 0x1B5, Name = "TRANSFORM_ARRAYLIST_TO_BOUNDED", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1B6, new OpcodeInfo { Opcode = 0x1B6, Name = "FREE_REF_PAK_N", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1B7, new OpcodeInfo { Opcode = 0x1B7, Name = "ARRAY_BOUND_INFO", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1B8, new OpcodeInfo { Opcode = 0x1B8, Name = "LOWERBOUND", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1B9, new OpcodeInfo { Opcode = 0x1B9, Name = "UPPERBOUND", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1BA, new OpcodeInfo { Opcode = 0x1BA, Name = "INCR_ANY", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x1BB, new OpcodeInfo { Opcode = 0x1BB, Name = "DECR_ANY", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x1BC, new OpcodeInfo { Opcode = 0x1BC, Name = "PUSH_FUNC_CLASS", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x1BD, new OpcodeInfo { Opcode = 0x1BD, Name = "CLASS_CALL", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x1BE, new OpcodeInfo { Opcode = 0x1BE, Name = "CLASS_CALL_DEC", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x1BF, new OpcodeInfo { Opcode = 0x1BF, Name = "CLASS_CALL_DOUBLE", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x1C0, new OpcodeInfo { Opcode = 0x1C0, Name = "CLASS_CALL_ANY", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x1C1, new OpcodeInfo { Opcode = 0x1C1, Name = "INDEX_RP", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1C2, new OpcodeInfo { Opcode = 0x1C2, Name = "DBDELETEWITHCURS", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1C3, new OpcodeInfo { Opcode = 0x1C3, Name = "DBEXECUTEIMMED", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x1C4, new OpcodeInfo { Opcode = 0x1C4, Name = "DBEXECDYNWITHDESC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1C5, new OpcodeInfo { Opcode = 0x1C5, Name = "DBFETCHWITHDESC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1C6, new OpcodeInfo { Opcode = 0x1C6, Name = "DBOPENDYNWITHDESC", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1C7, new OpcodeInfo { Opcode = 0x1C7, Name = "DBUPDATEWITHCURS", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1C8, new OpcodeInfo { Opcode = 0x1C8, Name = "CREATE_USING", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1C9, new OpcodeInfo { Opcode = 0x1C9, Name = "TRANSFORM_ANY_TO_UNBOUNDED", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1CA, new OpcodeInfo { Opcode = 0x1CA, Name = "TRANSFORM_ANY_TO_BOUNDED", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1CB, new OpcodeInfo { Opcode = 0x1CB, Name = "FREE_INV_METH_ARGS", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1CC, new OpcodeInfo { Opcode = 0x1CC, Name = "PUSH_NULL", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1CD, new OpcodeInfo { Opcode = 0x1CD, Name = "COPY_LVALUE_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1CE, new OpcodeInfo { Opcode = 0x1CE, Name = "ENTER_EMBEDDED", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1CF, new OpcodeInfo { Opcode = 0x1CF, Name = "EXIT_EMBEDDED", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1D0, new OpcodeInfo { Opcode = 0x1D0, Name = "DOT_FLD_UPDATE_INDEX_RP", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1D1, new OpcodeInfo { Opcode = 0x1D1, Name = "CNV_STRING_TO_BOUNDED_CHARARRAY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1D2, new OpcodeInfo { Opcode = 0x1D2, Name = "PUSH_NTH_PARENT", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1D3, new OpcodeInfo { Opcode = 0x1D3, Name = "MOD_LONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1D4, new OpcodeInfo { Opcode = 0x1D4, Name = "MOD_ULONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1D5, new OpcodeInfo { Opcode = 0x1D5, Name = "MOD_DOUBLE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1D6, new OpcodeInfo { Opcode = 0x1D6, Name = "MOD_DEC", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1D7, new OpcodeInfo { Opcode = 0x1D7, Name = "MOD_ANY", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1D8, new OpcodeInfo { Opcode = 0x1D8, Name = "ABS_DEC", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1D9, new OpcodeInfo { Opcode = 0x1D9, Name = "ABS_ANY", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1DA, new OpcodeInfo { Opcode = 0x1DA, Name = "CEILING_ANY", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1DB, new OpcodeInfo { Opcode = 0x1DB, Name = "MIN_LONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1DC, new OpcodeInfo { Opcode = 0x1DC, Name = "MIN_ULONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1DD, new OpcodeInfo { Opcode = 0x1DD, Name = "MIN_DOUBLE", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1DE, new OpcodeInfo { Opcode = 0x1DE, Name = "MIN_DEC", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1DF, new OpcodeInfo { Opcode = 0x1DF, Name = "MIN_ANY", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1E0, new OpcodeInfo { Opcode = 0x1E0, Name = "MAX_LONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1E1, new OpcodeInfo { Opcode = 0x1E1, Name = "MAX_ULONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1E2, new OpcodeInfo { Opcode = 0x1E2, Name = "MAX_DOUBLE", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1E3, new OpcodeInfo { Opcode = 0x1E3, Name = "MAX_DEC", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1E4, new OpcodeInfo { Opcode = 0x1E4, Name = "MAX_ANY", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x1E5, new OpcodeInfo { Opcode = 0x1E5, Name = "PUSH_TRY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1E6, new OpcodeInfo { Opcode = 0x1E6, Name = "POP_TRY", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1E7, new OpcodeInfo { Opcode = 0x1E7, Name = "CATCH_EXCEPTION", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1E8, new OpcodeInfo { Opcode = 0x1E8, Name = "THROW_EXCEPTION", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1E9, new OpcodeInfo { Opcode = 0x1E9, Name = "GOSUB", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1EA, new OpcodeInfo { Opcode = 0x1EA, Name = "RETURN_SUB", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x1EB, new OpcodeInfo { Opcode = 0x1EB, Name = "CNV_INT_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1EC, new OpcodeInfo { Opcode = 0x1EC, Name = "CNV_UINT_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1ED, new OpcodeInfo { Opcode = 0x1ED, Name = "CNV_LONG_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1EE, new OpcodeInfo { Opcode = 0x1EE, Name = "CNV_ULONG_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1EF, new OpcodeInfo { Opcode = 0x1EF, Name = "CNV_DEC_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1F0, new OpcodeInfo { Opcode = 0x1F0, Name = "CNV_FLOAT_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1F1, new OpcodeInfo { Opcode = 0x1F1, Name = "CNV_DOUBLE_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x1F2, new OpcodeInfo { Opcode = 0x1F2, Name = "CNV_LONGLONG_TO_INT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1F3, new OpcodeInfo { Opcode = 0x1F3, Name = "CNV_LONGLONG_TO_UINT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1F4, new OpcodeInfo { Opcode = 0x1F4, Name = "CNV_LONGLONG_TO_LONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1F5, new OpcodeInfo { Opcode = 0x1F5, Name = "CNV_LONGLONG_TO_ULONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1F6, new OpcodeInfo { Opcode = 0x1F6, Name = "CNV_LONGLONG_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1F7, new OpcodeInfo { Opcode = 0x1F7, Name = "CNV_LONGLONG_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1F8, new OpcodeInfo { Opcode = 0x1F8, Name = "CNV_LONGLONG_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x1F9, new OpcodeInfo { Opcode = 0x1F9, Name = "ADD_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1FA, new OpcodeInfo { Opcode = 0x1FA, Name = "ADD", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1FB, new OpcodeInfo { Opcode = 0x1FB, Name = "SUB", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1FC, new OpcodeInfo { Opcode = 0x1FC, Name = "DIV_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1FD, new OpcodeInfo { Opcode = 0x1FD, Name = "POWER_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x1FE, new OpcodeInfo { Opcode = 0x1FE, Name = "POWER", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x1FF, new OpcodeInfo { Opcode = 0x1FF, Name = "NEGATE", Length = 1, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x200, new OpcodeInfo { Opcode = 0x200, Name = "PUSH_LOCAL_VAR_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x201, new OpcodeInfo { Opcode = 0x201, Name = "PUSH_LOCAL_GLOBREF_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x202, new OpcodeInfo { Opcode = 0x202, Name = "PUSH_LOCAL_ARGREF_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x203, new OpcodeInfo { Opcode = 0x203, Name = "PUSH_SHARED_VAR_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 4" } },
            { 0x204, new OpcodeInfo { Opcode = 0x204, Name = "PUSH_SHARED_GLOBREF_LONGLONG", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x205, new OpcodeInfo { Opcode = 0x205, Name = "ASSIGN_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x206, new OpcodeInfo { Opcode = 0x206, Name = "COPY_CONST_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x207, new OpcodeInfo { Opcode = 0x207, Name = "ADDASSIGN_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x208, new OpcodeInfo { Opcode = 0x208, Name = "SUBASSIGN_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x209, new OpcodeInfo { Opcode = 0x209, Name = "MULTASSIGN_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x20A, new OpcodeInfo { Opcode = 0x20A, Name = "ASSIGN", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x20B, new OpcodeInfo { Opcode = 0x20B, Name = "DECR_LONGLONG", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x20C, new OpcodeInfo { Opcode = 0x20C, Name = "COPY_LVALUE_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x20D, new OpcodeInfo { Opcode = 0x20D, Name = "ABS_LONGLONG", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x20E, new OpcodeInfo { Opcode = 0x20E, Name = "RAND_LONGLONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x20F, new OpcodeInfo { Opcode = 0x20F, Name = "EQ_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x210, new OpcodeInfo { Opcode = 0x210, Name = "NE_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x211, new OpcodeInfo { Opcode = 0x211, Name = "GT_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x212, new OpcodeInfo { Opcode = 0x212, Name = "LT_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x213, new OpcodeInfo { Opcode = 0x213, Name = "GE_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x214, new OpcodeInfo { Opcode = 0x214, Name = "LE_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x215, new OpcodeInfo { Opcode = 0x215, Name = "MOD_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x216, new OpcodeInfo { Opcode = 0x216, Name = "MIN_LONGLONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x217, new OpcodeInfo { Opcode = 0x217, Name = "MAX_LONGLONG", Length = 1, Category = "sm", StackEffect = "5 -> 3" } },
            { 0x218, new OpcodeInfo { Opcode = 0x218, Name = "GLOBFUNCCALL_LONGLONG", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x219, new OpcodeInfo { Opcode = 0x219, Name = "SYSFUNCCALL_LONGLONG", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x21A, new OpcodeInfo { Opcode = 0x21A, Name = "DLLFUNCCALL_LONGLONG", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x21B, new OpcodeInfo { Opcode = 0x21B, Name = "DOTFUNCCALL_LONGLONG", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x21C, new OpcodeInfo { Opcode = 0x21C, Name = "CALL_FUNCTION", Length = 1, Category = "sm", StackEffect = "6 -> 10" } },
            { 0x21D, new OpcodeInfo { Opcode = 0x21D, Name = "COPY_EXPR_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x21E, new OpcodeInfo { Opcode = 0x21E, Name = "DOT_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x21F, new OpcodeInfo { Opcode = 0x21F, Name = "INDEX_LONGLONG", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x220, new OpcodeInfo { Opcode = 0x220, Name = "CNV_ANY_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x221, new OpcodeInfo { Opcode = 0x221, Name = "CONV_LONGLONG_RVALUE_TO_PTR", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x222, new OpcodeInfo { Opcode = 0x222, Name = "INDEX_ERR_CHK_LONGLONG", Length = 1, Category = "sm", StackEffect = "" } },
            { 0x223, new OpcodeInfo { Opcode = 0x223, Name = "PUSH_CONST_BYTE", Length = 1, Category = "sm", StackEffect = "0 -> 12" } },
            { 0x224, new OpcodeInfo { Opcode = 0x224, Name = "CNV_INT_TO_BYTE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x225, new OpcodeInfo { Opcode = 0x225, Name = "CNV_UINT_TO_BYTE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x226, new OpcodeInfo { Opcode = 0x226, Name = "CNV_LONG_TO_BYTE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x227, new OpcodeInfo { Opcode = 0x227, Name = "CNV_ULONG_TO_BYTE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x228, new OpcodeInfo { Opcode = 0x228, Name = "CNV_DEC_TO_BYTE", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x229, new OpcodeInfo { Opcode = 0x229, Name = "CNV_FLOAT_TO_BYTE", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x22A, new OpcodeInfo { Opcode = 0x22A, Name = "CNV_DOUBLE_TO_BYTE", Length = 1, Category = "sm", StackEffect = "1 -> 1" } },
            { 0x22B, new OpcodeInfo { Opcode = 0x22B, Name = "CNV_ANY_TO_BYTE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x22C, new OpcodeInfo { Opcode = 0x22C, Name = "CNV_LONGLONG_TO_BYTE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x22D, new OpcodeInfo { Opcode = 0x22D, Name = "CNV_BYTE_TO_INT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x22E, new OpcodeInfo { Opcode = 0x22E, Name = "CNV_BYTE_TO_UINT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x22F, new OpcodeInfo { Opcode = 0x22F, Name = "CNV_BYTE_TO_LONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x230, new OpcodeInfo { Opcode = 0x230, Name = "CNV_BYTE_TO_ULONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x231, new OpcodeInfo { Opcode = 0x231, Name = "CNV_BYTE_TO_DEC", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x232, new OpcodeInfo { Opcode = 0x232, Name = "CNV_BYTE_TO_FLOAT", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x233, new OpcodeInfo { Opcode = 0x233, Name = "CNV_BYTE_TO_DOUBLE", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x234, new OpcodeInfo { Opcode = 0x234, Name = "CNV_BYTE_TO_LONGLONG", Length = 1, Category = "sm", StackEffect = "0 -> 0" } },
            { 0x235, new OpcodeInfo { Opcode = 0x235, Name = "ADD_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x236, new OpcodeInfo { Opcode = 0x236, Name = "SUB_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x237, new OpcodeInfo { Opcode = 0x237, Name = "MULT_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x238, new OpcodeInfo { Opcode = 0x238, Name = "DIV_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x239, new OpcodeInfo { Opcode = 0x239, Name = "POWER_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x23A, new OpcodeInfo { Opcode = 0x23A, Name = "NEGATE_BYTE", Length = 1, Category = "sm", StackEffect = "1 -> 3" } },
            { 0x23B, new OpcodeInfo { Opcode = 0x23B, Name = "INCR_BYTE", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x23C, new OpcodeInfo { Opcode = 0x23C, Name = "DECR_BYTE", Length = 1, Category = "sm", StackEffect = "1 -> 0" } },
            { 0x23D, new OpcodeInfo { Opcode = 0x23D, Name = "ASSIGN_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x23E, new OpcodeInfo { Opcode = 0x23E, Name = "ADDASSIGN_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x23F, new OpcodeInfo { Opcode = 0x23F, Name = "SUBASSIGN_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x240, new OpcodeInfo { Opcode = 0x240, Name = "MULTASSIGN_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 0" } },
            { 0x241, new OpcodeInfo { Opcode = 0x241, Name = "EQ_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x242, new OpcodeInfo { Opcode = 0x242, Name = "NE_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x243, new OpcodeInfo { Opcode = 0x243, Name = "GT_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x244, new OpcodeInfo { Opcode = 0x244, Name = "LT_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x245, new OpcodeInfo { Opcode = 0x245, Name = "GE_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
            { 0x246, new OpcodeInfo { Opcode = 0x246, Name = "LE_BYTE", Length = 1, Category = "sm", StackEffect = "2 -> 1" } },
        };

        public static OpcodeInfo Get(ushort opcode) => _opcodes.TryGetValue(opcode, out var info) ? info : null;
    }
}
