[package]
name = "application"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
blake3 = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
