[package]
name = "adapters"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { workspace = true }
application = { workspace = true }
memmap2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
iced-x86 = { workspace = true }
blake3 = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled"], optional = true }

[features]
default = []
sqlite = ["rusqlite"]
