from __future__ import annotations

from .ast_nodes import (
    Assignment as ASTAssignment,
    Identifier,
    CaseExpression as CaseItem,  # Alias for test compatibility
    Label as LabelStatement,      # Alias for test compatibility
)

# Node imports from consolidated ast_nodes.py
from .ast_nodes import (
    # Base classes
    ASTNode,
    # Operators
    BinaryExpression,
    Block,
    BooleanLiteral,
    BooleanOperation,
    BreakStatement,
    # Case statements
    CaseExpression,
    CaseStatement,
    CatchBlock,
    # Control flow
    Condition,
    ContinueStatement,
    # Code generation
    ControlFlow,
    DoWhileLoop,
    RepeatUntilLoop,
    # Events
    Event,
    EventTrigger,
    # Exception handling
    ExceptionType,
    ExitStatement,
    Expression,
    FinallyBlock,
    ForLoop,
    GotoStatement,
    IfStatement,
    IntegerLiteral,
    # Goto
    Label,
    # Literals
    Literal,
    NullLiteral,
    RealLiteral,
    ReturnStatement,
    Statement,
    StringLiteral,
    ThrowStatement,
    TryCatchStatement,
    UnaryExpression,
    # Variables
    Variable,
    VariableDeclaration,
    WhileLoop,
)
from .functions import (
    Function,
    FunctionCall,
    FunctionDefinition,
    Parameter,
    ProcedureCall,
    ProcedureDefinition,
    Signature,
)
from .io import (
    CloseFile,
    FileManager,
    FileMode,
    FileOperation,
    OpenFile,
    ReadFile,
    WriteFile,
)
from .node_kind import NodeKind

# SQL Node imports
from .sql import (
    Assignment,
    ColonParameter,
    ColumnReference,
    DeleteStatement,
    FromClause,
    GroupByClause,
    HavingClause,
    InsertStatement,
    JoinClause,
    LimitClause,
    OrderByClause,
    OrderingTerm,
    QuestionMarkParameter,
    ResultColumn,
    SelectStatement,
    SetOperationStatement,
    SQLCommit,
    SQLCursor,
    SQLFromClause,
    SqlParameter,
    SQLPrepare,
    SQLQuery,
    SQLRollback,
    SqlStatement,
    SQLTransaction,
    SQLVariable,
    SubqueryExpression,
    TableReference,
    UpdateStatement,
    WhereClause,
    WithClause,
    WithExpression,
)
from .types import (
    ArrayAccess,
    ArrayAssignment,
    ArrayDeclaration,
    ArrayOperation,
    ArraySlice,
    ArrayType,
    BasicType,
    CustomType,
    Field,
    Structure,
    Type,
    TypeBounds,
    TypeCategory,
    TypeRegistry,
)

# PowerBuilder type imports
from .pb_types import (
    PBType,
    PBBasicType,
    PBCustomType,
    PBArrayType,
    PBDataWindowType,
    PBTypeNode,
    PBBasicTypeNode,
    PBCustomTypeNode,
    PBTypeRegistry,
    DataType,
    PBSourcedEntity,
)

__all__ = [
    "ASTAssignment",
    # Base nodes
    "ASTNode",
    "Identifier",
    "CaseItem",
    "LabelStatement",
    "ArrayAccess",
    "ArrayAssignment",
    # Array operations
    "ArrayDeclaration",
    "ArrayOperation",
    "ArraySlice",
    "ArrayType",
    # SQL Nodes
    "Assignment",
    "BasicType",
    "BinaryExpression",
    "Block",
    "BooleanLiteral",
    "BooleanOperation",
    "BreakStatement",
    # Case statements
    "CaseExpression",
    "CaseStatement",
    "CatchBlock",
    "CloseFile",
    "ColonParameter",
    "ColumnReference",
    # Control flow
    "Condition",
    "ContinueStatement",
    "ControlFlow",
    # Types
    "CustomType",
    "DeleteStatement",
    "DoWhileLoop",
    # Events and functions
    "Event",
    "EventTrigger",
    # Exception handling
    "ExceptionType",
    "ExitStatement",
    "Expression",
    # Structure
    "Field",
    # I/O
    "FileManager",
    "FileMode",
    "FileOperation",
    "FinallyBlock",
    "ForLoop",
    "FromClause",
    "Function",
    "FunctionDefinition",
    "GotoStatement",
    "GroupByClause",
    "HavingClause",
    "IfStatement",
    "InsertStatement",
    "IntegerLiteral",
    "JoinClause",
    # Goto
    "Label",
    "LimitClause",
    # Literals
    "Literal",
    "NodeKind",
    "NullLiteral",
    "OpenFile",
    "OrderByClause",
    "OrderingTerm",
    "Parameter",
    "ProcedureCall",
    "ProcedureDefinition",
    "QuestionMarkParameter",
    "ReadFile",
    "RealLiteral",
    "RepeatUntilLoop",
    "ResultColumn",
    "ReturnStatement",
    "SQLCommit",
    "SQLCursor",
    "SQLFromClause",
    "SQLPrepare",
    "SQLQuery",
    "SQLRollback",
    "SQLTransaction",
    "SQLVariable",
    "SelectStatement",
    "SetOperationStatement",
    "Signature",
    "SqlParameter",
    "SqlStatement",
    "Statement",
    "StringLiteral",
    "Structure",
    "SubqueryExpression",
    "TableReference",
    "ThrowStatement",
    "TryCatchStatement",
    "Type",
    "TypeBounds",
    # Type system
    "TypeCategory",
    "TypeRegistry",
    # PowerBuilder types
    "PBType",
    "PBBasicType",
    "PBCustomType",
    "PBArrayType",
    "PBDataWindowType",
    "PBTypeNode",
    "PBBasicTypeNode",
    "PBCustomTypeNode",
    "PBTypeRegistry",
    "DataType",
    "PBSourcedEntity",
    "UnaryExpression",
    "UpdateStatement",
    # Variables and expressions
    "Variable",
    "VariableDeclaration",
    "WhereClause",
    "WhileLoop",
    "WithClause",
    "WithExpression",
    "WriteFile",
]
