//! Documentation Generator
//!
//! Generates comprehensive Markdown documentation for migrated applications.

use domain::model::{CoreModule, UiTree};
use domain::translation::{EmissionUnit, EmitErr, EmittedFile, FeatureSet, TargetEmitter};
use std::collections::HashMap;

/// Documentation generator configuration
#[derive(Debug, Clone)]
pub struct DocsGeneratorConfig {
    pub project_name: String,
    pub version: String,
    pub include_diagrams: bool,
    pub include_api_docs: bool,
}

impl Default for DocsGeneratorConfig {
    fn default() -> Self {
        Self {
            project_name: "PowerBuilder Migration".to_string(),
            version: "1.0.0".to_string(),
            include_diagrams: true,
            include_api_docs: true,
        }
    }
}

pub struct DocsEmitter {
    config: DocsGeneratorConfig,
}

impl DocsEmitter {
    pub fn new(config: DocsGeneratorConfig) -> Self {
        Self { config }
    }

    /// Generate main README.md
    fn generate_readme(&self, ir: &CoreModule) -> String {
        format!(
            r#"# {}

**Version:** {}

Generated from PowerBuilder application using [PowerRebuilder](https://github.com/michaelprowacki/powerrebuilder).

## Overview

This project is a modern re-implementation of a PowerBuilder application, automatically translated to modern web technologies.

## Architecture

### Original PowerBuilder Components

- **Module:** {}
- **Functions:** {} functions extracted and translated
- **Domain Models:** Business logic preserved from original application

### Modern Stack

- **Frontend:** Flutter/React/Vue/Svelte (choose based on target)
- **Backend:** Python/Litestar REST API
- **Database:** SQLModel with SQLite/PostgreSQL
- **Deployment:** Docker-ready with CI/CD

## Project Structure

```
.
├── README.md              # This file
├── ARCHITECTURE.md        # System architecture documentation
├── API.md                # API endpoint documentation
├── DEPLOYMENT.md         # Deployment guide
├── MIGRATION_NOTES.md    # Migration-specific notes
└── modules/              # Module documentation
    └── {}.md
```

## Getting Started

### Prerequisites

- Python 3.11+
- Node.js 18+ (for frontend)
- Docker (optional, for deployment)

### Installation

See [DEPLOYMENT.md](DEPLOYMENT.md) for detailed installation instructions.

### Running the Application

```bash
# Backend API
cd api
python main.py

# Frontend (example for React)
cd frontend
npm install
npm run dev
```

## Documentation

- [Architecture Overview](ARCHITECTURE.md)
- [API Documentation](API.md)
- [Deployment Guide](DEPLOYMENT.md)
- [Migration Notes](MIGRATION_NOTES.md)

## Features Ported from PowerBuilder

✅ Business logic and domain models
✅ Database schema and relationships
✅ User interface components
✅ Data validation rules
✅ API endpoints for all operations

## Support

For issues or questions about the migration, please refer to the [PowerRebuilder documentation](https://github.com/michaelprowacki/powerrebuilder).

## License

Generated by PowerRebuilder - {} version {}
"#,
            self.config.project_name,
            self.config.version,
            ir.id,
            ir.items.len(),
            ir.id,
            self.config.project_name,
            self.config.version
        )
    }

    /// Generate ARCHITECTURE.md
    fn generate_architecture_doc(&self, ir: &CoreModule) -> String {
        format!(
            r#"# Architecture Documentation

## System Overview

This document describes the architecture of the {} application, migrated from PowerBuilder to modern web technologies.

## Bounded Contexts

The application follows Domain-Driven Design (DDD) principles with clear bounded contexts:

### Core Domain

**Module:** {}

The core domain contains the essential business logic extracted from the PowerBuilder application.

#### Items

{}

## Layers

### Domain Layer

Pure business logic with no dependencies on infrastructure.

- **Entities:** Core business objects
- **Value Objects:** Immutable domain concepts
- **Domain Events:** Business-significant occurrences
- **Repositories:** Interfaces for persistence

### Application Layer

Orchestrates domain operations and use cases.

- **Commands:** Write operations
- **Queries:** Read operations
- **Handlers:** Command/Query processing logic
- **DTOs:** Data transfer objects

### Infrastructure Layer

Technical concerns and external integrations.

- **Database:** SQLModel with async SQLAlchemy
- **API:** Litestar REST endpoints
- **Frontend:** React/Vue/Flutter components

## Design Patterns

### Functional Domain Modeling

Following Scott Wlaschin's principles:

1. **Make illegal states unrepresentable** - Type-driven design
2. **Railway-oriented programming** - Result types for error handling
3. **Parse, don't validate** - Validation at boundaries
4. **Pure functions** - Domain logic without side effects

### CQRS Pattern

Commands and Queries are separated for clarity:

- **Commands:** Modify state, return events
- **Queries:** Read state, never modify

### Repository Pattern

Data access abstraction:

```
Domain → IRepository → SQLModel Repository
```

## Data Flow

```
UI → API → Application → Domain → Repository → Database
     ↓
   Events
```

1. User interacts with UI
2. API receives HTTP request
3. Application layer processes command/query
4. Domain layer executes business logic
5. Repository persists changes
6. Events emitted for side effects

## Technology Stack

| Layer | Technology | Purpose |
|-------|-----------|---------|
| Frontend | React/Vue/Flutter | User interface |
| API | Litestar | REST endpoints |
| Domain | Pure Python | Business logic |
| Data | SQLModel | Database models |
| Database | PostgreSQL/SQLite | Persistence |
| Deployment | Docker | Containerization |

## Security

- JWT authentication
- Role-based access control (RBAC)
- Input validation with Pydantic
- SQL injection prevention via SQLModel
- CORS configuration

## Performance

- Async/await for I/O operations
- Database connection pooling
- Response caching where appropriate
- Lazy loading of relationships

## Testing Strategy

- **Unit Tests:** Domain logic (pure functions)
- **Integration Tests:** API endpoints
- **E2E Tests:** Complete user flows

## Deployment

See [DEPLOYMENT.md](DEPLOYMENT.md) for deployment instructions.
"#,
            self.config.project_name,
            ir.id,
            self.format_items(&ir.items)
        )
    }

    /// Generate API.md documentation
    fn generate_api_doc(&self) -> String {
        r#"# API Documentation

## Base URL

```
Development: http://localhost:8000
Production: https://api.yourapp.com
```

## Authentication

All endpoints require JWT authentication except for `/auth/login`.

Include the token in the Authorization header:

```
Authorization: Bearer <your_jwt_token>
```

## Endpoints

### Authentication

#### POST /auth/login

Authenticate and receive JWT token.

**Request:**

```json
{
  "username": "user@example.com",
  "password": "password123"
}
```

**Response:**

```json
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...",
  "token_type": "bearer",
  "expires_in": 3600
}
```

### Entities

#### GET /api/entities

List all entities with pagination.

**Query Parameters:**

- `limit` (integer, default: 100) - Maximum number of results
- `offset` (integer, default: 0) - Number of results to skip

**Response:**

```json
[
  {
    "id": 1,
    "name": "Entity 1",
    "description": "Description",
    "created_at": "2024-01-01T00:00:00Z",
    "updated_at": "2024-01-01T00:00:00Z"
  }
]
```

#### GET /api/entities/{id}

Get entity by ID.

**Path Parameters:**

- `id` (integer) - Entity ID

**Response:**

```json
{
  "id": 1,
  "name": "Entity 1",
  "description": "Description",
  "created_at": "2024-01-01T00:00:00Z",
  "updated_at": "2024-01-01T00:00:00Z"
}
```

#### POST /api/entities

Create new entity.

**Request:**

```json
{
  "name": "New Entity",
  "description": "Description"
}
```

**Response:**

```json
{
  "id": 2,
  "name": "New Entity",
  "description": "Description",
  "created_at": "2024-01-01T00:00:00Z",
  "updated_at": "2024-01-01T00:00:00Z"
}
```

#### PUT /api/entities/{id}

Update entity.

**Path Parameters:**

- `id` (integer) - Entity ID

**Request:**

```json
{
  "name": "Updated Entity",
  "description": "Updated description"
}
```

**Response:**

```json
{
  "id": 1,
  "name": "Updated Entity",
  "description": "Updated description",
  "created_at": "2024-01-01T00:00:00Z",
  "updated_at": "2024-01-01T12:00:00Z"
}
```

#### DELETE /api/entities/{id}

Delete entity.

**Path Parameters:**

- `id` (integer) - Entity ID

**Response:**

```
204 No Content
```

## Error Responses

All endpoints may return these error responses:

### 400 Bad Request

Invalid request data.

```json
{
  "detail": "Validation error",
  "errors": [
    {
      "field": "name",
      "message": "This field is required"
    }
  ]
}
```

### 401 Unauthorized

Missing or invalid authentication token.

```json
{
  "detail": "Not authenticated"
}
```

### 404 Not Found

Resource not found.

```json
{
  "detail": "Entity 123 not found"
}
```

### 500 Internal Server Error

Server error.

```json
{
  "detail": "Internal server error"
}
```

## Rate Limiting

API requests are rate-limited to 1000 requests per hour per user.

## OpenAPI Specification

Interactive API documentation is available at:

- Swagger UI: http://localhost:8000/schema
- ReDoc: http://localhost:8000/schema/redoc
- OpenAPI JSON: http://localhost:8000/schema/openapi.json
"#
        .to_string()
    }

    /// Generate DEPLOYMENT.md
    fn generate_deployment_doc(&self) -> String {
        format!(
            r#"# Deployment Guide

## Prerequisites

- Docker and Docker Compose
- Python 3.11+
- Node.js 18+
- PostgreSQL 14+ (for production)

## Local Development

### Backend

1. Create virtual environment:

```bash
cd api
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
```

2. Install dependencies:

```bash
pip install -e .
```

3. Set up environment:

```bash
cp .env.example .env
# Edit .env with your configuration
```

4. Run migrations:

```bash
alembic upgrade head
```

5. Start development server:

```bash
python main.py
```

API will be available at http://localhost:8000

### Frontend

1. Install dependencies:

```bash
cd frontend
npm install
```

2. Set up environment:

```bash
cp .env.example .env
# Edit .env with API URL
```

3. Start development server:

```bash
npm run dev
```

Frontend will be available at http://localhost:3000

## Docker Deployment

### Build and Run

```bash
docker-compose up -d
```

This will start:

- API server on port 8000
- Frontend on port 3000
- PostgreSQL on port 5432

### Environment Variables

Create `.env` file with:

```env
DATABASE_URL=postgresql://user:password@db:5432/dbname
SECRET_KEY=your-secret-key-here
CORS_ORIGINS=http://localhost:3000,https://yourapp.com
```

## Production Deployment

### AWS (recommended)

1. **Database:** Amazon RDS (PostgreSQL)
2. **Backend:** AWS ECS/Fargate or EC2
3. **Frontend:** AWS S3 + CloudFront
4. **Secrets:** AWS Secrets Manager

### Deploy with AWS CDK

```bash
cd infra
npm install
cdk deploy
```

### Heroku

```bash
heroku create {}
heroku addons:create heroku-postgresql:hobby-dev
git push heroku main
```

### Digital Ocean

1. Create PostgreSQL database
2. Create App Platform app
3. Connect GitHub repository
4. Set environment variables
5. Deploy

## Monitoring

### Health Check

```bash
curl http://localhost:8000/health
```

### Logs

```bash
docker-compose logs -f api
```

### Metrics

Prometheus metrics available at:

```
http://localhost:8000/metrics
```

## Backup and Recovery

### Database Backup

```bash
docker-compose exec db pg_dump -U user dbname > backup.sql
```

### Database Restore

```bash
docker-compose exec -T db psql -U user dbname < backup.sql
```

## Scaling

### Horizontal Scaling

Run multiple API instances behind a load balancer:

```bash
docker-compose up -d --scale api=3
```

### Vertical Scaling

Increase resources in `docker-compose.yml`:

```yaml
services:
  api:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
```

## Security Checklist

- [ ] Change default SECRET_KEY
- [ ] Use HTTPS in production
- [ ] Enable rate limiting
- [ ] Set up firewall rules
- [ ] Regular security updates
- [ ] Database backups
- [ ] Monitor logs for suspicious activity

## Troubleshooting

### Database Connection Issues

Check DATABASE_URL and ensure PostgreSQL is running:

```bash
docker-compose ps
```

### API Not Responding

Check logs:

```bash
docker-compose logs api
```

### Frontend Build Errors

Clear node_modules and rebuild:

```bash
rm -rf node_modules package-lock.json
npm install
npm run build
```
"#,
            self.config.project_name.to_lowercase().replace(' ', "-")
        )
    }

    /// Generate MIGRATION_NOTES.md
    fn generate_migration_notes(&self, ir: &CoreModule) -> String {
        format!(
            r#"# Migration Notes

## PowerBuilder to Modern Stack

This document describes specific migration decisions and considerations for the {} project.

## Original PowerBuilder Application

**Module:** {}
**Functions Extracted:** {}
**Migration Date:** {}

## Migration Decisions

### Database Schema

The original PowerBuilder database schema has been preserved with the following enhancements:

- Added `created_at` and `updated_at` timestamps to all tables
- Converted PowerBuilder data types to SQL standard types
- Normalized relationships where appropriate
- Added proper indexes for performance

### Business Logic

All business logic from PowerBuilder has been extracted and reimplemented:

- ✅ Data validation rules
- ✅ Computed fields and expressions
- ✅ Event handlers
- ✅ Window/form logic

### User Interface

The PowerBuilder UI has been modernized:

- Windows → React/Vue/Flutter components
- DataWindows → Data grids with sorting/filtering
- Menus → Navigation bars
- Buttons/Controls → Modern UI components

### Data Types Mapping

| PowerBuilder Type | Modern Type | Notes |
|------------------|-------------|-------|
| String | str | UTF-8 strings |
| Integer | int | 32-bit integers |
| Long | int | 64-bit integers |
| Decimal | Decimal | Precise decimal arithmetic |
| Date | date | Date only |
| DateTime | datetime | Date and time with timezone |
| Boolean | bool | True/False |
| Blob | bytes | Binary data |

### Known Limitations

#### Not Migrated

- PowerBuilder-specific UI effects (3D borders, etc.)
- Some legacy database drivers
- Embedded SQL with vendor-specific syntax

#### Partial Migration

- DataWindow compute expressions (converted to Python functions)
- Report generation (requires manual implementation)
- Some advanced DataWindow features

### Performance Considerations

The migrated application should match or exceed PowerBuilder performance:

- **Database:** Async queries instead of blocking
- **API:** REST instead of direct database connection
- **UI:** Modern reactive frameworks
- **Caching:** Added where beneficial

### Testing Coverage

Post-migration testing should cover:

- [ ] All API endpoints
- [ ] Database CRUD operations
- [ ] Business logic validation
- [ ] UI component rendering
- [ ] Integration tests
- [ ] Load testing

### Future Enhancements

Consider these improvements post-migration:

1. **GraphQL API** - Alternative to REST
2. **Real-time Updates** - WebSocket support
3. **Advanced Search** - Full-text search with Elasticsearch
4. **File Storage** - S3-compatible object storage
5. **Analytics** - Usage tracking and metrics

## Support

For issues specific to the migration process:

1. Check the [GitHub Issues](https://github.com/michaelprowacki/powerrebuilder/issues)
2. Review the PowerRebuilder documentation
3. Contact the migration team

## References

- [PowerBuilder Documentation](https://docs.appeon.com/pb2022/)
- [Litestar Documentation](https://litestar.dev/)
- [SQLModel Documentation](https://sqlmodel.tiangolo.com/)
- [React Documentation](https://react.dev/)
"#,
            self.config.project_name,
            ir.id,
            ir.items.len(),
            chrono::Utc::now().format("%Y-%m-%d")
        )
    }

    /// Format items list
    fn format_items(&self, items: &[domain::model::CoreItem]) -> String {
        if items.is_empty() {
            return "No items documented.".to_string();
        }

        items
            .iter()
            .map(|item| {
                use domain::model::CoreItem;
                match item {
                    CoreItem::Fn { sig, .. } => format!("- **Function**: {}", sig.name),
                    CoreItem::Data { def } => format!("- **Data**: {}", def.name),
                    CoreItem::Extern { sig } => format!("- **Extern**: {}", sig.name),
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    }
}

impl TargetEmitter for DocsEmitter {
    fn target_id(&self) -> &'static str {
        "docs"
    }

    fn supports(&self, features: &FeatureSet) -> bool {
        // Documentation generator supports all features
        true
    }

    fn emit_core(&self, ir: &CoreModule) -> Result<EmissionUnit, EmitErr> {
        let mut files = vec![];

        // Generate README.md
        files.push(EmittedFile {
            path: "README.md".to_string(),
            content: self.generate_readme(ir),
            is_executable: false,
        });

        // Generate ARCHITECTURE.md
        files.push(EmittedFile {
            path: "ARCHITECTURE.md".to_string(),
            content: self.generate_architecture_doc(ir),
            is_executable: false,
        });

        // Generate API.md
        if self.config.include_api_docs {
            files.push(EmittedFile {
                path: "API.md".to_string(),
                content: self.generate_api_doc(),
                is_executable: false,
            });
        }

        // Generate DEPLOYMENT.md
        files.push(EmittedFile {
            path: "DEPLOYMENT.md".to_string(),
            content: self.generate_deployment_doc(),
            is_executable: false,
        });

        // Generate MIGRATION_NOTES.md
        files.push(EmittedFile {
            path: "MIGRATION_NOTES.md".to_string(),
            content: self.generate_migration_notes(ir),
            is_executable: false,
        });

        Ok(EmissionUnit {
            files,
            metadata: HashMap::new(),
        })
    }

    fn emit_ui(&self, ui: &UiTree) -> Result<EmissionUnit, EmitErr> {
        // Documentation doesn't emit UI-specific files
        Ok(EmissionUnit {
            files: vec![],
            metadata: HashMap::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_docs_emitter() {
        let config = DocsGeneratorConfig::default();
        let emitter = DocsEmitter::new(config);
        assert_eq!(emitter.target_id(), "docs");
    }
}
